import 'dart:typed_data';

import 'package:firebirdpod/firebirdpod.dart';
import 'package:test/test.dart';

import 'firebird_test_support.dart';

void main() {
  group('Phase 01 direct fbclient features', () {
    setUpAll(() async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await buildDirectEndpoint(
        database: firebirdTestDatabasePath(),
      ).connect();
      try {
        await connection.execute('''
          recreate table FIREBIRDPOD_INSERT_TEST (
            ID bigint generated by default as identity primary key,
            NAME varchar(40) not null unique
          )
        ''');
      } finally {
        await connection.close();
      }
    });

    tearDownAll(() async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await buildDirectEndpoint(
        database: firebirdTestDatabasePath(),
      ).connect();
      try {
        await connection.execute('drop table FIREBIRDPOD_INSERT_TEST');
      } catch (_) {
      } finally {
        await connection.close();
      }
    });

    test('insert returning exposes generatedId for identity values', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await buildDirectEndpoint(
        database: firebirdTestDatabasePath(),
      ).connect();
      addTearDown(connection.close);

      final result = await connection.execute(
        r'''
        insert into FIREBIRDPOD_INSERT_TEST (NAME)
        values ($1)
        returning ID
        ''',
        parameters: FirebirdStatementParameters.positional(['alpha']),
      );

      expect(result.singleRow?['ID'], 1);
      expect(result.generatedId(), 1);
    });

    test('server-side failures are mapped to FirebirdDatabaseException', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await buildDirectEndpoint(
        database: firebirdTestDatabasePath(),
      ).connect();
      addTearDown(connection.close);

      await connection.execute(
        r'''
        insert into FIREBIRDPOD_INSERT_TEST (NAME)
        values ($1)
        ''',
        parameters: FirebirdStatementParameters.positional(['duplicate']),
      );

      await expectLater(
        () => connection.execute(
          r'''
          insert into FIREBIRDPOD_INSERT_TEST (NAME)
          values ($1)
          ''',
          parameters: FirebirdStatementParameters.positional(['duplicate']),
        ),
        throwsA(
          isA<FirebirdDatabaseException>()
              .having((error) => error.operation, 'operation', 'execute')
              .having((error) => error.message, 'message', isNotEmpty)
              .having(
                (error) => error.primaryErrorCode,
                'primaryErrorCode',
                isNotNull,
              )
              .having((error) => error.errorCodes, 'errorCodes', isNotEmpty),
        ),
      );
    });

    test('statement timeout surfaces as a timeout-mapped database exception', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await buildDirectEndpoint(
        database: firebirdTestDatabasePath(),
      ).connect();
      addTearDown(connection.close);

      await expectLater(
        () => connection.execute(
          '''
          select count(*)
          from rdb\$types a
          cross join rdb\$types b
          cross join rdb\$types c
          cross join rdb\$types d
          cross join rdb\$types e
          ''',
          timeout: const Duration(milliseconds: 20),
        ),
        throwsA(
          isA<FirebirdDatabaseException>().having(
            (error) => error.isTimeout,
            'isTimeout',
            isTrue,
          ),
        ),
      );
    });

    test('blob and richer Firebird 5 values round-trip through the adapter', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await buildDirectEndpoint(
        database: firebirdTestDatabasePath(),
      ).connect();
      addTearDown(connection.close);

      final result = await connection.execute(
        r'''
        select
          cast($1 as blob sub_type text) as text_blob,
          cast($2 as blob sub_type binary) as binary_blob,
          cast($3 as int128) as huge_int,
          cast($4 as numeric(38, 4)) as scaled_num,
          cast($5 as decfloat(16)) as dec16_value,
          cast($6 as decfloat(34)) as dec34_value,
          cast($7 as time with time zone) as event_time,
          cast($8 as timestamp with time zone) as created_at
        from rdb$database
        ''',
        parameters: FirebirdStatementParameters.positional([
          'hello firebird',
          Uint8List.fromList([1, 2, 3, 4]),
          BigInt.parse('12345678901234567890'),
          const FirebirdDecimal('12345678901234567890.1234'),
          const FirebirdDecimal('12345.6789'),
          const FirebirdDecimal('12345678901234567890123456789012.5'),
          const FirebirdTimeWithTimeZone(
            hour: 14,
            minute: 15,
            second: 16,
            millisecond: 17,
            tenthMillisecond: 2,
          ),
          const FirebirdTimestampWithTimeZone(
            year: 2025,
            month: 4,
            day: 16,
            hour: 14,
            minute: 15,
            second: 16,
            millisecond: 17,
            tenthMillisecond: 2,
          ),
        ]),
      );

      final row = result.singleRow!;
      expect(row['TEXT_BLOB'], 'hello firebird');
      expect(row['BINARY_BLOB'], Uint8List.fromList([1, 2, 3, 4]));
      expect(row['HUGE_INT'], BigInt.parse('12345678901234567890'));
      expect(
        row['SCALED_NUM'],
        const FirebirdDecimal('12345678901234567890.1234'),
      );
      expect(row['DEC16_VALUE'], const FirebirdDecimal('12345.6789'));
      expect(
        row['DEC34_VALUE'],
        const FirebirdDecimal('12345678901234567890123456789012.5'),
      );
      expect(row['EVENT_TIME'], isA<FirebirdTimeWithTimeZone>());
      expect(row['CREATED_AT'], isA<FirebirdTimestampWithTimeZone>());
    });
  });
}
