import 'package:firebirdpod/firebirdpod.dart';
import 'package:test/test.dart';

import 'firebird_test_support.dart';

const _tableName = 'FIREBIRDPOD_TX_CAP_ITEM';

void main() {
  group('Phase 01 explicit transaction capabilities', () {
    setUpAll(() async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await _openConnection();
      try {
        await _dropTableIfExists(connection, _tableName);
        await connection.execute('''
          create table $_tableName (
            ID integer generated by default as identity primary key,
            NAME varchar(50) not null
          )
        ''');
      } finally {
        await connection.close();
      }
    });

    tearDownAll(() async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await _openConnection();
      try {
        await _dropTableIfExists(connection, _tableName);
      } finally {
        await connection.close();
      }
    });

    setUp(() async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await _openConnection();
      try {
        await connection.execute('delete from $_tableName');
        await connection.execute(
          'alter table $_tableName alter ID restart with 1',
        );
      } finally {
        await connection.close();
      }
    });

    test('savepoint rollback preserves only pre-savepoint writes', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await _openConnection();
      addTearDown(connection.close);

      final transaction = await connection.beginTransaction();
      addTearDown(transaction.close);

      await transaction.execute(
        'insert into $_tableName (NAME) values (\$1)',
        parameters: FirebirdStatementParameters.positional(['before']),
      );

      final savepoint = await transaction.createSavepoint();

      await transaction.execute(
        'insert into $_tableName (NAME) values (\$1)',
        parameters: FirebirdStatementParameters.positional(['after']),
      );

      await savepoint.rollback();
      await savepoint.release();
      await transaction.commit();

      final rows = await connection.execute(
        'select NAME from $_tableName order by ID',
      );
      expect(
        rows.rows.map((row) => row['NAME']).toList(),
        ['before'],
      );
    });

    test('isolation settings map to Firebird transaction context', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      await _expectIsolationLevel(
        settings: const FirebirdTransactionSettings(
          isolationLevel: FirebirdTransactionIsolationLevel.readUncommitted,
        ),
        expectedIsolationLevel: 'READ COMMITTED',
      );

      await _expectIsolationLevel(
        settings: const FirebirdTransactionSettings(
          isolationLevel: FirebirdTransactionIsolationLevel.readCommitted,
        ),
        expectedIsolationLevel: 'READ COMMITTED',
        readOnly: true,
        expectedReadOnly: 'TRUE',
      );

      await _expectIsolationLevel(
        settings: const FirebirdTransactionSettings(
          isolationLevel: FirebirdTransactionIsolationLevel.repeatableRead,
        ),
        expectedIsolationLevel: 'SNAPSHOT',
      );

      await _expectIsolationLevel(
        settings: const FirebirdTransactionSettings(
          isolationLevel: FirebirdTransactionIsolationLevel.serializable,
        ),
        expectedIsolationLevel: 'CONSISTENCY',
      );
    });

    test(
      'runtime parameters are stored in USER_TRANSACTION context and mirrored locally',
      () async {
        if (!shouldRunDirectIntegrationTests()) {
          return;
        }

        final connection = await _openConnection();
        addTearDown(connection.close);

        final transaction = await connection.beginTransaction();
        addTearDown(transaction.close);

        await transaction.setRuntimeParameters((params) {
          return [
            params.transactionContextValue('REQUEST_ID', 'req-123'),
            params.transactionContextValues({
              'TENANT_ID': 44,
              'TRACE_ENABLED': true,
            }),
          ];
        });

        expect(transaction.runtimeParameters, {
          'REQUEST_ID': 'req-123',
          'TENANT_ID': 44,
          'TRACE_ENABLED': true,
        });

        final requestId = await transaction.execute(
          '''
          select rdb\$get_context('USER_TRANSACTION', \$1) as CTX_VALUE
          from rdb\$database
          ''',
          parameters: FirebirdStatementParameters.positional(['REQUEST_ID']),
        );
        final tenantId = await transaction.execute(
          '''
          select rdb\$get_context('USER_TRANSACTION', \$1) as CTX_VALUE
          from rdb\$database
          ''',
          parameters: FirebirdStatementParameters.positional(['TENANT_ID']),
        );
        final traceEnabled = await transaction.execute(
          '''
          select rdb\$get_context('USER_TRANSACTION', \$1) as CTX_VALUE
          from rdb\$database
          ''',
          parameters: FirebirdStatementParameters.positional(['TRACE_ENABLED']),
        );

        expect(requestId.singleRow?['CTX_VALUE'], 'req-123');
        expect(tenantId.singleRow?['CTX_VALUE'], '44');
        expect(traceEnabled.singleRow?['CTX_VALUE'], 'true');
      },
    );
  });
}

Future<void> _expectIsolationLevel({
  required FirebirdTransactionSettings settings,
  required String expectedIsolationLevel,
  bool readOnly = false,
  String expectedReadOnly = 'FALSE',
}) async {
  final connection = await _openConnection();
  addTearDown(connection.close);

  final transaction = await connection.beginTransaction(
    readOnly: readOnly,
    settings: settings,
  );
  addTearDown(transaction.close);

  final result = await transaction.execute('''
    select
      rdb\$get_context('SYSTEM', 'ISOLATION_LEVEL') as ISOLATION_LEVEL,
      rdb\$get_context('SYSTEM', 'READ_ONLY') as READ_ONLY
    from rdb\$database
  ''');

  expect(result.singleRow?['ISOLATION_LEVEL'], expectedIsolationLevel);
  expect(
    (result.singleRow?['READ_ONLY'] as String?)?.toUpperCase(),
    expectedReadOnly,
  );

  await transaction.rollback();
}

FirebirdEndpoint _buildEndpoint() {
  return buildDirectEndpoint(database: firebirdTestDatabasePath());
}

Future<FirebirdConnection> _openConnection() async {
  return _buildEndpoint().connect();
}

Future<void> _dropTableIfExists(
  FirebirdConnection connection,
  String tableName,
) async {
  try {
    await connection.execute('drop table $tableName');
  } catch (_) {}
}
