import 'dart:io';

import 'package:firebirdpod/firebirdpod.dart';
import 'package:serverpod_database/serverpod_database.dart';
import 'package:test/test.dart';

import 'firebird_test_support.dart';

const _tableName = 'FIREBIRDPOD_SERVERPOD_WRITE';

class _WriteRow implements TableRow<int?> {
  _WriteRow({
    required this.id,
    required this.name,
    required this.flag,
    required this.note,
    required this.createdAt,
    this.localTag,
  });

  factory _WriteRow.fromJson(Map<String, dynamic> json) {
    final createdAt = json['createdAt'];
    return _WriteRow(
      id: json['id'] as int?,
      name: json['name'] as String,
      flag: json['flag'] as bool,
      note: json['note'] as String?,
      createdAt: createdAt is DateTime
          ? createdAt
          : DateTime.parse(createdAt as String),
      localTag: json['localTag'] as String?,
    );
  }

  static final _WriteTable _table = _WriteTable();

  @override
  final int? id;

  final String name;
  final bool flag;
  final String? note;
  final DateTime createdAt;
  final String? localTag;

  @override
  _WriteTable get table => _table;

  @override
  Map<String, dynamic> toJson() => {
    'id': id,
    'name': name,
    'flag': flag,
    'note': note,
    'createdAt': createdAt,
    'localTag': localTag,
  };
}

class _WriteTable extends Table<int?> {
  _WriteTable() : super(tableName: _tableName);

  late final ColumnString name = ColumnString('name', this);
  late final ColumnBool flag = ColumnBool('flag', this);
  late final ColumnString note = ColumnString('note', this);
  late final ColumnDateTime createdAt = ColumnDateTime(
    'created_at',
    this,
    fieldName: 'createdAt',
  );

  @override
  List<Column> get columns => [id, name, flag, note, createdAt];
}

class _WriteSerializationManager extends SerializationManagerServer {
  final _WriteTable table = _WriteRow._table;

  @override
  T deserialize<T>(dynamic data, [Type? t]) {
    t ??= T;
    if (t == _WriteRow) {
      return _WriteRow.fromJson(Map<String, dynamic>.from(data)) as T;
    }
    return super.deserialize<T>(data, t);
  }

  @override
  String getModuleName() => 'test';

  @override
  Table? getTableForType(Type t) => t == _WriteRow ? table : null;

  @override
  List<TableDefinition> getTargetTableDefinitions() => const [];
}

class _TestDatabaseSession implements DatabaseSession {
  @override
  Transaction? transaction;

  @override
  Database get db => throw UnimplementedError('Database wrapper not needed.');

  @override
  LogQueryFunction? get logQuery => null;

  @override
  LogWarningFunction? get logWarning => null;
}

void main() {
  group('Phase 02 Serverpod generated write bridge', () {
    late FirebirdServerpodDatabaseConnection connection;
    final table = _WriteRow._table;

    setUpAll(() async {
      registerFirebirdServerpodDialect();
      connection = _buildConnection();

      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      await connection.simpleExecute(
        session,
        '''
        recreate table $_tableName (
          ID integer generated by default as identity primary key,
          NAME varchar(60) not null unique,
          FLAG boolean not null,
          NOTE varchar(120),
          CREATED_AT timestamp not null
        )
        ''',
      );
    });

    tearDownAll(() async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      try {
        await connection.simpleExecute(session, 'drop table $_tableName');
      } catch (_) {}
    });

    setUp(() async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      await connection.simpleExecute(session, 'delete from $_tableName');
      await connection.simpleExecute(
        session,
        'alter table $_tableName alter ID restart with 1',
      );
      await _seedRows(connection);
    });

    test('insertRow assigns generated ids and preserves non-persistent fields', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      final inserted = await connection.insertRow<_WriteRow>(
        session,
        _WriteRow(
          id: null,
          name: 'echo',
          flag: false,
          note: 'note-e',
          createdAt: DateTime.parse('2026-04-15 12:00:00'),
          localTag: 'client-only',
        ),
      );

      expect(inserted.id, 5);
      expect(inserted.name, 'echo');
      expect(inserted.localTag, 'client-only');

      final stored = await connection.findById<_WriteRow>(session, 5);
      expect(stored?.name, 'echo');
      expect(stored?.localTag, isNull);
    });

    test('insert preserves input order for multiple rows', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      final rows = await connection.insert<_WriteRow>(
        session,
        [
          _WriteRow(
            id: null,
            name: 'foxtrot',
            flag: true,
            note: 'note-f',
            createdAt: DateTime.parse('2026-04-15 12:10:00'),
            localTag: 'first',
          ),
          _WriteRow(
            id: null,
            name: 'golf',
            flag: false,
            note: 'note-g',
            createdAt: DateTime.parse('2026-04-15 12:20:00'),
            localTag: 'second',
          ),
        ],
      );

      expect(rows.map((row) => row.name), ['foxtrot', 'golf']);
      expect(rows.map((row) => row.id), [5, 6]);
      expect(rows.map((row) => row.localTag), ['first', 'second']);
    });

    test('insert runs multi-row writes atomically', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();

      await expectLater(
        () => connection.insert<_WriteRow>(
          session,
          [
            _WriteRow(
              id: null,
              name: 'hotel',
              flag: true,
              note: 'note-h',
              createdAt: DateTime.parse('2026-04-15 12:30:00'),
            ),
            _WriteRow(
              id: null,
              name: 'alpha',
              flag: false,
              note: 'duplicate-name',
              createdAt: DateTime.parse('2026-04-15 12:40:00'),
            ),
          ],
        ),
        throwsA(isA<FirebirdDatabaseException>()),
      );

      expect(await connection.count<_WriteRow>(session), 4);
      expect(
        await connection.findFirstRow<_WriteRow>(
          session,
          where: table.name.equals('hotel'),
        ),
        isNull,
      );
    });

    test('insert ignoreConflicts is rejected clearly for now', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      await expectLater(
        () => connection.insert<_WriteRow>(
          session,
          [
            _WriteRow(
              id: null,
              name: 'india',
              flag: true,
              note: null,
              createdAt: DateTime.parse('2026-04-15 12:50:00'),
            ),
          ],
          ignoreConflicts: true,
        ),
        throwsA(
          isA<UnsupportedError>().having(
            (error) => error.message,
            'message',
            contains('ignoreConflicts'),
          ),
        ),
      );
    });

    test('updateRow preserves non-persistent fields on the returned model', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      final updated = await connection.updateRow<_WriteRow>(
        session,
        _WriteRow(
          id: 1,
          name: 'alpha-updated',
          flag: false,
          note: 'note-a2',
          createdAt: DateTime.parse('2026-04-15 08:05:00'),
          localTag: 'kept-local',
        ),
      );

      expect(updated.name, 'alpha-updated');
      expect(updated.flag, isFalse);
      expect(updated.localTag, 'kept-local');

      final stored = await connection.findById<_WriteRow>(session, 1);
      expect(stored?.name, 'alpha-updated');
      expect(stored?.localTag, isNull);
    });

    test('update preserves input order for multiple rows', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      final updated = await connection.update<_WriteRow>(
        session,
        [
          _WriteRow(
            id: 3,
            name: 'charlie',
            flag: false,
            note: 'updated-c',
            createdAt: DateTime.parse('2026-04-15 10:00:00'),
            localTag: 'third',
          ),
          _WriteRow(
            id: 1,
            name: 'alpha',
            flag: true,
            note: 'updated-a',
            createdAt: DateTime.parse('2026-04-15 08:00:00'),
            localTag: 'first',
          ),
        ],
      );

      expect(updated.map((row) => row.id), [3, 1]);
      expect(updated.map((row) => row.localTag), ['third', 'first']);
      expect(updated.map((row) => row.note), ['updated-c', 'updated-a']);
    });

    test('updateById applies selected column values and returns the updated row', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      final updated = await connection.updateById<_WriteRow>(
        session,
        2,
        columnValues: [
          ColumnValue<String, String?>(table.note, 'note-b2'),
          ColumnValue<bool, bool?>(table.flag, true),
        ],
      );

      expect(updated.id, 2);
      expect(updated.note, 'note-b2');
      expect(updated.flag, isTrue);
    });

    test('updateWhere applies ordered limited updates and returns rows in selection order', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      final updated = await connection.updateWhere<_WriteRow>(
        session,
        where: table.flag.equals(true),
        orderBy: table.createdAt,
        limit: 1,
        offset: 1,
        columnValues: [
          ColumnValue<String, String?>(table.note, 'selected-update'),
        ],
      );

      expect(updated, hasLength(1));
      expect(updated.single.id, 3);
      expect(updated.single.note, 'selected-update');

      final unchanged = await connection.findById<_WriteRow>(session, 4);
      expect(unchanged?.note, 'note-d');
    });

    test('lockRows supports FOR UPDATE inside explicit transactions', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();

      await connection.transaction<void>(
        (transaction) async {
          await connection.lockRows<_WriteRow>(
            session,
            where: table.id.equals(3),
            lockMode: LockMode.forUpdate,
            transaction: transaction,
          );

          final row = await connection.findById<_WriteRow>(
            session,
            3,
            transaction: transaction,
          );

          expect(row?.name, 'charlie');
        },
        settings: const TransactionSettings(),
        session: session,
      );
    });

    test('deleteRow returns the deleted row', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      final deleted = await connection.deleteRow<_WriteRow>(
        session,
        _WriteRow(
          id: 2,
          name: 'bravo',
          flag: false,
          note: 'note-b',
          createdAt: DateTime.parse('2026-04-15 09:00:00'),
        ),
      );

      expect(deleted.id, 2);
      expect(await connection.findById<_WriteRow>(session, 2), isNull);
    });

    test('delete preserves ordered selection for multiple rows', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      final deleted = await connection.delete<_WriteRow>(
        session,
        [
          _WriteRow(
            id: 4,
            name: 'delta',
            flag: true,
            note: 'note-d',
            createdAt: DateTime.parse('2026-04-15 11:00:00'),
          ),
          _WriteRow(
            id: 2,
            name: 'bravo',
            flag: false,
            note: 'note-b',
            createdAt: DateTime.parse('2026-04-15 09:00:00'),
          ),
        ],
        orderBy: table.id,
      );

      expect(deleted.map((row) => row.id), [2, 4]);
      expect(await connection.count<_WriteRow>(session), 2);
    });

    test('deleteWhere respects ordered selection and returns deleted rows in order', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      final deleted = await connection.deleteWhere<_WriteRow>(
        session,
        table.flag.equals(true),
        orderBy: table.createdAt.desc(),
      );

      expect(deleted.map((row) => row.id), [4, 3, 1]);
      expect(await connection.count<_WriteRow>(session), 1);
    });
  });
}

FirebirdServerpodDatabaseConnection _buildConnection() {
  final provider = DatabaseProvider.forDialect(DatabaseDialect.firebird)
      as FirebirdServerpodDatabaseProvider;
  final poolManager = provider.createPoolManager(
    _WriteSerializationManager(),
    null,
    FirebirdServerpodDatabaseConfig(
      host: Platform.environment['FIREBIRDPOD_TEST_HOST'] ?? 'localhost',
      port: _testPort(),
      user: firebirdTestUser(),
      password: firebirdTestPassword(),
      name: firebirdTestDatabasePath(),
      fbClientLibraryPath: firebirdClientLibraryPath(),
    ),
  );
  return provider.createConnection(poolManager);
}

Future<void> _seedRows(FirebirdServerpodDatabaseConnection connection) async {
  final session = _TestDatabaseSession();
  final inserts = <String>[
    "insert into $_tableName (NAME, FLAG, NOTE, CREATED_AT) values ('alpha', TRUE, NULL, '2026-04-15 08:00:00')",
    "insert into $_tableName (NAME, FLAG, NOTE, CREATED_AT) values ('bravo', FALSE, 'note-b', '2026-04-15 09:00:00')",
    "insert into $_tableName (NAME, FLAG, NOTE, CREATED_AT) values ('charlie', TRUE, 'note-c', '2026-04-15 10:00:00')",
    "insert into $_tableName (NAME, FLAG, NOTE, CREATED_AT) values ('delta', TRUE, 'note-d', '2026-04-15 11:00:00')",
  ];

  for (final sql in inserts) {
    await connection.simpleExecute(session, sql);
  }
}

int _testPort() {
  final value = Platform.environment['FIREBIRDPOD_TEST_PORT'];
  if (value == null || value.isEmpty) return 3050;
  return int.parse(value);
}
