import 'package:firebirdpod/firebirdpod.dart';
import 'package:serverpod_database/serverpod_database.dart';
import 'package:test/test.dart';

void main() {
  const generator = FirebirdServerpodSqlGenerator();

  group('Firebird Serverpod SQL generator', () {
    test('generates deterministic Firebird definition SQL', () {
      final databaseDefinition = DatabaseDefinition(
        moduleName: 'app',
        tables: [
          TableDefinition(
            name: 'parent',
            dartName: 'Parent',
            schema: 'public',
            columns: [
              ColumnDefinition(
                name: 'id',
                columnType: ColumnType.bigint,
                isNullable: false,
                columnDefault: defaultIntSerial,
              ),
              ColumnDefinition(
                name: 'name',
                columnType: ColumnType.text,
                isNullable: false,
              ),
              ColumnDefinition(
                name: 'isActive',
                columnType: ColumnType.boolean,
                isNullable: false,
                columnDefault: defaultBooleanTrue,
              ),
              ColumnDefinition(
                name: 'createdAt',
                columnType: ColumnType.timestampWithoutTimeZone,
                isNullable: false,
                columnDefault: defaultDateTimeValueNow,
              ),
              ColumnDefinition(
                name: 'publicId',
                columnType: ColumnType.uuid,
                isNullable: false,
              ),
            ],
            foreignKeys: const [],
            indexes: [
              IndexDefinition(
                indexName: 'parent_pkey',
                elements: [
                  IndexElementDefinition(
                    type: IndexElementDefinitionType.column,
                    definition: 'id',
                  ),
                ],
                type: 'btree',
                isUnique: true,
                isPrimary: true,
              ),
              IndexDefinition(
                indexName: 'parent_public_id_idx',
                elements: [
                  IndexElementDefinition(
                    type: IndexElementDefinitionType.column,
                    definition: 'publicId',
                  ),
                ],
                type: 'btree',
                isUnique: true,
                isPrimary: false,
              ),
            ],
          ),
          TableDefinition(
            name: 'child',
            dartName: 'Child',
            schema: 'public',
            columns: [
              ColumnDefinition(
                name: 'id',
                columnType: ColumnType.bigint,
                isNullable: false,
                columnDefault: defaultIntSerial,
              ),
              ColumnDefinition(
                name: 'parentId',
                columnType: ColumnType.bigint,
                isNullable: false,
              ),
              ColumnDefinition(
                name: 'payload',
                columnType: ColumnType.json,
                isNullable: true,
              ),
            ],
            foreignKeys: [
              ForeignKeyDefinition(
                constraintName: 'child_parent_fk',
                columns: const ['parentId'],
                referenceTable: 'parent',
                referenceTableSchema: 'public',
                referenceColumns: const ['id'],
                onDelete: ForeignKeyAction.cascade,
              ),
            ],
            indexes: const [],
          ),
        ],
        installedModules: const [],
        migrationApiVersion: 1,
      );

      final sql = generator.generateDatabaseDefinitionSql(
        databaseDefinition,
        installedModules: [
          DatabaseMigrationVersionModel(
            module: 'app',
            version: '202604160001',
            timestamp: DateTime.utc(2026, 4, 16, 1, 2, 3, 456),
          ),
        ],
      );

      expect(
        sql,
        equals('''
--
-- Class Parent as table parent
--
CREATE TABLE "parent" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" BLOB SUB_TYPE TEXT CHARACTER SET UTF8 NOT NULL,
  "isActive" BOOLEAN DEFAULT TRUE NOT NULL,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "publicId" CHAR(36) CHARACTER SET ASCII NOT NULL
);
CREATE UNIQUE INDEX "parent_public_id_idx" ON "parent" ("publicId");

--
-- Class Child as table child
--
CREATE TABLE "child" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parentId" BIGINT NOT NULL,
  "payload" BLOB SUB_TYPE TEXT CHARACTER SET UTF8,
  CONSTRAINT "child_parent_fk" FOREIGN KEY ("parentId") REFERENCES "parent" ("id") ON DELETE CASCADE
);

UPDATE OR INSERT INTO "serverpod_migrations" ("module", "version", "timestamp") VALUES ('app', '202604160001', TIMESTAMP '2026-04-16 01:02:03.456') MATCHING ("module");
'''),
      );
    });

    test('wraps create table if not exists in Firebird execute block', () {
      final databaseMigration = DatabaseMigration(
        actions: [
          DatabaseMigrationAction(
            type: DatabaseMigrationActionType.createTableIfNotExists,
            createTable: TableDefinition(
              name: 'audit_log',
              dartName: 'AuditLog',
              schema: 'public',
              columns: [
                ColumnDefinition(
                  name: 'id',
                  columnType: ColumnType.bigint,
                  isNullable: false,
                  columnDefault: defaultIntSerial,
                ),
                ColumnDefinition(
                  name: 'event',
                  columnType: ColumnType.text,
                  isNullable: false,
                ),
              ],
              foreignKeys: const [],
              indexes: [
                IndexDefinition(
                  indexName: 'audit_log_event_idx',
                  elements: [
                    IndexElementDefinition(
                      type: IndexElementDefinitionType.column,
                      definition: 'event',
                    ),
                  ],
                  type: 'btree',
                  isUnique: false,
                  isPrimary: false,
                ),
              ],
            ),
          ),
        ],
        warnings: const [],
        migrationApiVersion: 1,
      );

      final sql = generator.generateDatabaseMigrationSql(
        databaseMigration,
        DatabaseDefinition(
          moduleName: 'app',
          tables: [
            TableDefinition(
              name: 'audit_log',
              dartName: 'AuditLog',
              schema: 'public',
              columns: [
                ColumnDefinition(
                  name: 'id',
                  columnType: ColumnType.bigint,
                  isNullable: false,
                  columnDefault: defaultIntSerial,
                ),
                ColumnDefinition(
                  name: 'event',
                  columnType: ColumnType.text,
                  isNullable: false,
                ),
              ],
              foreignKeys: const [],
              indexes: [
                IndexDefinition(
                  indexName: 'audit_log_event_idx',
                  elements: [
                    IndexElementDefinition(
                      type: IndexElementDefinitionType.column,
                      definition: 'event',
                    ),
                  ],
                  type: 'btree',
                  isUnique: false,
                  isPrimary: false,
                ),
              ],
            ),
          ],
          installedModules: const [],
          migrationApiVersion: 1,
        ),
        installedModules: const [],
        removedModules: const [],
      );

      expect(
        sql,
        equals('''
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB\$RELATIONS WHERE RDB\$RELATION_NAME = 'AUDIT_LOG' AND COALESCE(RDB\$SYSTEM_FLAG, 0) = 0)) THEN
  BEGIN
    EXECUTE STATEMENT 'CREATE TABLE "audit_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event" BLOB SUB_TYPE TEXT CHARACTER SET UTF8 NOT NULL
)';
    EXECUTE STATEMENT 'CREATE INDEX "audit_log_event_idx" ON "audit_log" ("event")';
  END
END;
'''),
      );
    });

    test('generates alter table migration SQL for supported operations', () {
      final targetDefinition = DatabaseDefinition(
        moduleName: 'app',
        tables: [
          TableDefinition(
            name: 'task',
            dartName: 'Task',
            schema: 'public',
            columns: [
              ColumnDefinition(
                name: 'id',
                columnType: ColumnType.bigint,
                isNullable: false,
                columnDefault: defaultIntSerial,
              ),
              ColumnDefinition(
                name: 'title',
                columnType: ColumnType.text,
                isNullable: false,
              ),
              ColumnDefinition(
                name: 'createdAt',
                columnType: ColumnType.timestampWithoutTimeZone,
                isNullable: false,
                columnDefault: defaultDateTimeValueNow,
              ),
              ColumnDefinition(
                name: 'ownerId',
                columnType: ColumnType.bigint,
                isNullable: true,
              ),
            ],
            foreignKeys: [
              ForeignKeyDefinition(
                constraintName: 'task_owner_fk',
                columns: const ['ownerId'],
                referenceTable: 'app_user',
                referenceTableSchema: 'public',
                referenceColumns: const ['id'],
                onDelete: ForeignKeyAction.setNull,
              ),
            ],
            indexes: [
              IndexDefinition(
                indexName: 'task_title_idx',
                elements: [
                  IndexElementDefinition(
                    type: IndexElementDefinitionType.column,
                    definition: 'title',
                  ),
                ],
                type: 'btree',
                isUnique: false,
                isPrimary: false,
              ),
            ],
          ),
        ],
        installedModules: const [],
        migrationApiVersion: 1,
      );

      final databaseMigration = DatabaseMigration(
        actions: [
          DatabaseMigrationAction(
            type: DatabaseMigrationActionType.alterTable,
            alterTable: TableMigration(
              name: 'task',
              schema: 'public',
              addColumns: [
                ColumnDefinition(
                  name: 'createdAt',
                  columnType: ColumnType.timestampWithoutTimeZone,
                  isNullable: false,
                  columnDefault: defaultDateTimeValueNow,
                ),
              ],
              deleteColumns: const ['legacyTitle'],
              modifyColumns: [
                ColumnMigration(
                  columnName: 'ownerId',
                  addNullable: false,
                  removeNullable: true,
                  changeDefault: false,
                ),
                ColumnMigration(
                  columnName: 'title',
                  addNullable: false,
                  removeNullable: false,
                  changeDefault: true,
                  newDefault: null,
                ),
              ],
              renameColumns: const {'name': 'title'},
              addIndexes: [
                IndexDefinition(
                  indexName: 'task_title_idx',
                  elements: [
                    IndexElementDefinition(
                      type: IndexElementDefinitionType.column,
                      definition: 'title',
                    ),
                  ],
                  type: 'btree',
                  isUnique: false,
                  isPrimary: false,
                ),
              ],
              deleteIndexes: const ['task_old_name_idx'],
              addForeignKeys: [
                ForeignKeyDefinition(
                  constraintName: 'task_owner_fk',
                  columns: const ['ownerId'],
                  referenceTable: 'app_user',
                  referenceTableSchema: 'public',
                  referenceColumns: const ['id'],
                  onDelete: ForeignKeyAction.setNull,
                ),
              ],
              deleteForeignKeys: const ['task_old_fk'],
              warnings: const [],
            ),
          ),
        ],
        warnings: const [],
        migrationApiVersion: 1,
      );

      final sql = generator.generateDatabaseMigrationSql(
        databaseMigration,
        targetDefinition,
        installedModules: [
          DatabaseMigrationVersionModel(module: 'app', version: '202604160002'),
        ],
        removedModules: [
          DatabaseMigrationVersionModel(
            module: 'old_module',
            version: '202604150999',
          ),
        ],
      );

      expect(
        sql,
        equals('''
DROP INDEX "task_old_name_idx";
ALTER TABLE "task" DROP CONSTRAINT "task_old_fk";
ALTER TABLE "task" DROP "legacyTitle";
ALTER TABLE "task" ALTER COLUMN "name" TO "title";
ALTER TABLE "task" ADD "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE "task" ALTER COLUMN "ownerId" SET NOT NULL;
ALTER TABLE "task" ALTER COLUMN "title" DROP DEFAULT;
CREATE INDEX "task_title_idx" ON "task" ("title");
ALTER TABLE "task" ADD CONSTRAINT "task_owner_fk" FOREIGN KEY ("ownerId") REFERENCES "app_user" ("id") ON DELETE SET NULL;

DELETE FROM "serverpod_migrations" WHERE "module" = 'old_module';
UPDATE OR INSERT INTO "serverpod_migrations" ("module", "version", "timestamp") VALUES ('app', '202604160002', CURRENT_TIMESTAMP) MATCHING ("module");
'''),
      );
    });

    test('rejects unsupported Firebird schema features clearly', () {
      final databaseDefinition = DatabaseDefinition(
        moduleName: 'app',
        tables: [
          TableDefinition(
            name: 'vector_table',
            dartName: 'VectorTable',
            schema: 'custom_schema',
            columns: [
              ColumnDefinition(
                name: 'id',
                columnType: ColumnType.bigint,
                isNullable: false,
                columnDefault: defaultIntSerial,
              ),
            ],
            foreignKeys: const [],
            indexes: const [],
          ),
        ],
        installedModules: const [],
        migrationApiVersion: 1,
      );

      expect(
        () => generator.generateDatabaseDefinitionSql(
          databaseDefinition,
          installedModules: const [],
        ),
        throwsA(
          isA<UnsupportedError>().having(
            (error) => error.message,
            'message',
            contains('supports only the "public" Serverpod schema mapping'),
          ),
        ),
      );

      final randomUuidDefaultDefinition = DatabaseDefinition(
        moduleName: 'app',
        tables: [
          TableDefinition(
            name: 'uuid_table',
            dartName: 'UuidTable',
            schema: 'public',
            columns: [
              ColumnDefinition(
                name: 'id',
                columnType: ColumnType.bigint,
                isNullable: false,
                columnDefault: defaultIntSerial,
              ),
              ColumnDefinition(
                name: 'publicId',
                columnType: ColumnType.uuid,
                isNullable: false,
                columnDefault: defaultUuidValueRandom,
              ),
            ],
            foreignKeys: const [],
            indexes: const [],
          ),
        ],
        installedModules: const [],
        migrationApiVersion: 1,
      );

      expect(
        () => generator.generateDatabaseDefinitionSql(
          randomUuidDefaultDefinition,
          installedModules: const [],
        ),
        throwsA(
          isA<UnsupportedError>().having(
            (error) => error.message,
            'message',
            contains('does not support random UUID defaults yet'),
          ),
        ),
      );
    });
  });
}
