import 'dart:async';

import 'package:firebirdpod/firebirdpod.dart';
import 'package:test/test.dart';

import 'firebird_test_support.dart';

const _stressTable = 'FIREBIRDPOD_STRESS_ITEM';

void main() {
  group('Phase 01 direct fbclient stress', () {
    setUpAll(() async {
      if (!shouldRunDirectStressTests()) {
        return;
      }

      final connection = await _openConnection();
      try {
        await _dropTableIfExists(connection, _stressTable);
        await connection.execute('''
          create table $_stressTable (
            ID bigint generated by default as identity primary key,
            LABEL varchar(50) not null unique
          )
        ''');
      } finally {
        await connection.close();
      }
    });

    tearDownAll(() async {
      if (!shouldRunDirectStressTests()) {
        return;
      }

      final connection = await _openConnection();
      try {
        await _dropTableIfExists(connection, _stressTable);
      } finally {
        await connection.close();
      }
    });

    setUp(() async {
      if (!shouldRunDirectStressTests()) {
        return;
      }

      final connection = await _openConnection();
      try {
        await connection.execute('delete from $_stressTable');
        await connection.execute(
          'alter table $_stressTable alter ID restart with 1',
        );
      } finally {
        await connection.close();
      }
    });

    test(
      'repeated attach and close returns global monitor counts to baseline',
      () async {
        if (!shouldRunDirectStressTests()) {
          return;
        }

        final iterations = firebirdStressIterations();
        final monitor = await _openConnection();
        addTearDown(monitor.close);

        final baseline = await _captureExternalSnapshot(monitor);
        for (var iteration = 0; iteration < iterations; iteration++) {
          final connection = await _openConnection();
          try {
            final result = await connection.execute(
              'select 1 as RESULT_VALUE from rdb\$database',
            );
            expect(result.singleRow?['RESULT_VALUE'], 1);
          } finally {
            await connection.close();
          }
        }

        await _expectExternalSnapshot(
          monitor,
          baseline,
          reason:
              'attach/close loop should not leak attachments, transactions, or statements',
        );
      },
    );

    test(
      'repeated prepare execute close leaves no worker statements behind',
      () async {
        if (!shouldRunDirectStressTests()) {
          return;
        }

        final iterations = firebirdStressIterations();
        final monitor = await _openConnection();
        addTearDown(monitor.close);

        final worker = await _openConnection();
        addTearDown(worker.close);

        final workerAttachmentId = await _currentConnectionId(worker);
        final baseline = await _expectAttachmentSnapshot(
          monitor,
          workerAttachmentId,
          expectedStatementCount: 0,
          expectedTransactionCount: 1,
          expectedAttachmentCount: 1,
          reason:
              'worker should begin the statement loop with one retained transaction and no leaked statements',
        );

        for (var iteration = 0; iteration < iterations; iteration++) {
          final statement = await worker.prepare(
            'select current_connection as CONN_ID, cast(\$1 as integer) as LOOP_VALUE from rdb\$database',
          );
          try {
            final result = await statement.execute(
              FirebirdStatementParameters.positional([iteration]),
            );
            expect(result.singleRow?['CONN_ID'], workerAttachmentId);
            expect(result.singleRow?['LOOP_VALUE'], iteration);
          } finally {
            await statement.close();
          }
        }

        await _expectAttachmentSnapshot(
          monitor,
          workerAttachmentId,
          expectedStatementCount: baseline.statementCount,
          expectedTransactionCount: baseline.transactionCount,
          expectedAttachmentCount: baseline.attachmentCount,
          reason:
              'prepare/execute/close loop should not leave statements behind on the worker attachment',
        );
      },
    );

    test(
      'repeated commit and rollback loops return worker transactions to baseline',
      () async {
        if (!shouldRunDirectStressTests()) {
          return;
        }

        final iterations = firebirdStressIterations();
        final monitor = await _openConnection();
        addTearDown(monitor.close);

        final worker = await _openConnection();
        addTearDown(worker.close);

        final workerAttachmentId = await _currentConnectionId(worker);
        final baseline = await _expectAttachmentSnapshot(
          monitor,
          workerAttachmentId,
          expectedStatementCount: 0,
          expectedTransactionCount: 1,
          expectedAttachmentCount: 1,
          reason:
              'worker should begin the transaction loop with one retained transaction and no leaked statements',
        );

        for (var iteration = 0; iteration < iterations; iteration++) {
          final commitTransaction = await worker.beginTransaction();
          try {
            final insertResult = await commitTransaction.execute(
              '''
            insert into $_stressTable (LABEL)
            values (\$1)
            returning ID
            ''',
              parameters: FirebirdStatementParameters.positional([
                'commit-$iteration',
              ]),
            );
            final generatedId = insertResult.generatedId();
            expect(generatedId, isA<int>());

            final deleteResult = await commitTransaction.execute(
              '''
            delete from $_stressTable
            where id = \$1
            ''',
              parameters: FirebirdStatementParameters.positional([generatedId]),
            );
            expect(deleteResult.affectedRows, 1);
            await commitTransaction.commit();
          } finally {
            await commitTransaction.close();
          }

          final rollbackTransaction = await worker.beginTransaction();
          try {
            await rollbackTransaction.execute(
              '''
            insert into $_stressTable (LABEL)
            values (\$1)
            ''',
              parameters: FirebirdStatementParameters.positional([
                'rollback-$iteration',
              ]),
            );
            await rollbackTransaction.rollback();
          } finally {
            await rollbackTransaction.close();
          }
        }

        expect(await _countRows(worker, _stressTable), 0);
        await _expectAttachmentSnapshot(
          monitor,
          workerAttachmentId,
          expectedStatementCount: baseline.statementCount,
          expectedTransactionCount: baseline.transactionCount,
          expectedAttachmentCount: baseline.attachmentCount,
          reason:
              'commit and rollback loops should return the worker attachment to its retained baseline',
        );
      },
    );

    test('repeated retained failures do not leak worker state', () async {
      if (!shouldRunDirectStressTests()) {
        return;
      }

      final iterations = firebirdStressIterations();
      final monitor = await _openConnection();
      addTearDown(monitor.close);

      final worker = await _openConnection();
      addTearDown(worker.close);

      await worker.execute('''
        insert into $_stressTable (LABEL)
        values (\$1)
        ''', parameters: FirebirdStatementParameters.positional(['seed']));

      final workerAttachmentId = await _currentConnectionId(worker);
      final baseline = await _expectAttachmentSnapshot(
        monitor,
        workerAttachmentId,
        expectedStatementCount: 0,
        expectedTransactionCount: 1,
        expectedAttachmentCount: 1,
        reason:
            'worker should begin the failure loop with one retained transaction and no leaked statements',
      );

      for (var iteration = 0; iteration < iterations; iteration++) {
        final error = await _captureDbException(() {
          return worker.execute('''
            insert into $_stressTable (LABEL)
            values (\$1)
            ''', parameters: FirebirdStatementParameters.positional(['seed']));
        });
        expect(error.operation, 'execute');
        expect(error.primaryErrorCode, isNotNull);
      }

      expect(await _countRows(worker, _stressTable), 1);
      await _expectAttachmentSnapshot(
        monitor,
        workerAttachmentId,
        expectedStatementCount: baseline.statementCount,
        expectedTransactionCount: baseline.transactionCount,
        expectedAttachmentCount: baseline.attachmentCount,
        reason:
            'retained failure loop should not leave statements or extra transactions behind',
      );
    });

    test(
      'repeated resetForReuse cycles return the worker attachment to its retained baseline',
      () async {
        if (!shouldRunDirectStressTests()) {
          return;
        }

        final iterations = firebirdStressIterations();
        final monitor = await _openConnection();
        addTearDown(monitor.close);

        final worker = await _openConnection();
        addTearDown(worker.close);

        final workerAttachmentId = await _currentConnectionId(worker);
        final baseline = await _expectAttachmentSnapshot(
          monitor,
          workerAttachmentId,
          expectedStatementCount: 0,
          expectedTransactionCount: 1,
          expectedAttachmentCount: 1,
          reason:
              'worker should begin the pooled-reset loop with one retained transaction and no leaked statements',
        );

        for (var iteration = 0; iteration < iterations; iteration++) {
          final retainedStatement = await worker.prepare(
            'select cast(\$1 as integer) as LOOP_VALUE from rdb\$database',
          );
          final transaction = await worker.beginTransaction();
          final transactionStatement = await transaction.prepare('''
          insert into $_stressTable (LABEL)
          values (\$1)
          ''');
          await transaction.createSavepoint();

          final retainedResult = await retainedStatement.execute(
            FirebirdStatementParameters.positional([iteration]),
          );
          expect(retainedResult.singleRow?['LOOP_VALUE'], iteration);

          await worker.execute(
            '''
          select rdb\$set_context('USER_TRANSACTION', \$1, \$2) as APPLIED
          from rdb\$database
          ''',
            parameters: FirebirdStatementParameters.positional([
              'RESET_MARKER',
              'iteration-$iteration',
            ]),
          );

          await transactionStatement.execute(
            FirebirdStatementParameters.positional(['pending-$iteration']),
          );

          await worker.resetForReuse();

          expect(retainedStatement.isClosed, isTrue);
          expect(transactionStatement.isClosed, isTrue);
          expect(transaction.isRolledBack, isTrue);
          expect(transaction.isClosed, isTrue);
          expect(
            await _transactionContextValue(worker, 'RESET_MARKER'),
            anyOf(isNull, ''),
          );
          expect(await _countRows(worker, _stressTable), 0);

          await _expectAttachmentSnapshot(
            monitor,
            workerAttachmentId,
            expectedStatementCount: baseline.statementCount,
            expectedTransactionCount: baseline.transactionCount,
            expectedAttachmentCount: baseline.attachmentCount,
            reason:
                'pooled reset loop should return the worker attachment to its retained baseline after every reset',
          );
        }
      },
    );
  });
}

Future<FirebirdConnection> _openConnection() {
  return buildDirectEndpoint(database: firebirdTestDatabasePath()).connect();
}

Future<void> _dropTableIfExists(
  FirebirdConnection connection,
  String tableName,
) async {
  try {
    await connection.execute('drop table $tableName');
  } on FirebirdDatabaseException {
    // Ignore cleanup if the table does not exist yet.
  }
}

Future<int> _currentConnectionId(FirebirdConnection connection) async {
  final result = await connection.execute(
    'select current_connection as CONN_ID from rdb\$database',
  );
  return result.singleRow!['CONN_ID'] as int;
}

Future<int> _countRows(FirebirdConnection connection, String tableName) async {
  final result = await connection.execute(
    'select count(*) as RESULT_TOTAL from $tableName',
  );
  return result.singleRow!['RESULT_TOTAL'] as int;
}

Future<Object?> _transactionContextValue(
  FirebirdConnection connection,
  String key,
) async {
  final result = await connection.execute('''
    select rdb\$get_context('USER_TRANSACTION', \$1) as RESULT_VALUE
    from rdb\$database
    ''', parameters: FirebirdStatementParameters.positional([key]));
  return result.singleRow?['RESULT_VALUE'];
}

Future<FirebirdDatabaseException> _captureDbException(
  Future<Object?> Function() action,
) async {
  try {
    await action();
  } on FirebirdDatabaseException catch (error) {
    return error;
  }

  fail('Expected FirebirdDatabaseException to be thrown.');
}

Future<_ExternalSnapshot> _captureExternalSnapshot(
  FirebirdConnection monitor,
) async {
  final attachmentIds = await _fetchIds(
    monitor,
    'select mon\$attachment_id as ITEM_ID from mon\$attachments where mon\$attachment_id <> current_connection order by 1',
  );
  final transactionIds = await _fetchIds(
    monitor,
    'select mon\$transaction_id as ITEM_ID from mon\$transactions where mon\$attachment_id <> current_connection order by 1',
  );
  final statementIds = await _fetchIds(
    monitor,
    'select mon\$statement_id as ITEM_ID from mon\$statements where mon\$attachment_id <> current_connection order by 1',
  );

  return _ExternalSnapshot(
    attachmentIds: attachmentIds,
    transactionIds: transactionIds,
    statementIds: statementIds,
  );
}

Future<_AttachmentSnapshot> _captureAttachmentSnapshot(
  FirebirdConnection monitor,
  int attachmentId,
) async {
  final attachmentIds = await _fetchIds(
    monitor,
    '''
    select mon\$attachment_id as ITEM_ID
    from mon\$attachments
    where mon\$attachment_id = \$1
    order by 1
    ''',
    [attachmentId],
  );
  final transactionIds = await _fetchIds(
    monitor,
    '''
    select mon\$transaction_id as ITEM_ID
    from mon\$transactions
    where mon\$attachment_id = \$1
    order by 1
    ''',
    [attachmentId],
  );
  final statementIds = await _fetchIds(
    monitor,
    '''
    select mon\$statement_id as ITEM_ID
    from mon\$statements
    where mon\$attachment_id = \$1
    order by 1
    ''',
    [attachmentId],
  );

  return _AttachmentSnapshot(
    attachmentId: attachmentId,
    attachmentIds: attachmentIds,
    transactionIds: transactionIds,
    statementIds: statementIds,
  );
}

Future<List<int>> _fetchIds(
  FirebirdConnection connection,
  String sql, [
  List<Object?> values = const [],
]) async {
  final result = await connection.execute(
    sql,
    parameters: FirebirdStatementParameters.positional(values),
  );
  return result.rows
      .map((row) => row['ITEM_ID'] as int)
      .toList(growable: false);
}

Future<void> _expectExternalSnapshot(
  FirebirdConnection monitor,
  _ExternalSnapshot expected, {
  required String reason,
}) async {
  final actual = await _eventually(
    () async => _captureExternalSnapshot(monitor),
    (snapshot) =>
        snapshot.attachmentIds.length == expected.attachmentIds.length &&
        snapshot.transactionIds.length == expected.transactionIds.length &&
        snapshot.statementIds.length == expected.statementIds.length,
  );

  expect(actual.attachmentIds, expected.attachmentIds, reason: reason);
  expect(actual.transactionIds, expected.transactionIds, reason: reason);
  expect(actual.statementIds, expected.statementIds, reason: reason);
}

Future<_AttachmentSnapshot> _expectAttachmentSnapshot(
  FirebirdConnection monitor,
  int attachmentId, {
  required int expectedStatementCount,
  required int expectedTransactionCount,
  required int expectedAttachmentCount,
  required String reason,
}) async {
  final actual = await _eventually(
    () async => _captureAttachmentSnapshot(monitor, attachmentId),
    (snapshot) =>
        snapshot.statementCount == expectedStatementCount &&
        snapshot.transactionCount == expectedTransactionCount &&
        snapshot.attachmentCount == expectedAttachmentCount,
  );

  expect(actual.statementCount, expectedStatementCount, reason: reason);
  expect(actual.transactionCount, expectedTransactionCount, reason: reason);
  expect(actual.attachmentCount, expectedAttachmentCount, reason: reason);
  return actual;
}

Future<T> _eventually<T>(
  Future<T> Function() read,
  bool Function(T value) isDone,
) async {
  late T lastValue;
  for (var attempt = 0; attempt < 20; attempt++) {
    lastValue = await read();
    if (isDone(lastValue)) {
      return lastValue;
    }
    await Future<void>.delayed(const Duration(milliseconds: 50));
  }
  return lastValue;
}

class _ExternalSnapshot {
  const _ExternalSnapshot({
    required this.attachmentIds,
    required this.transactionIds,
    required this.statementIds,
  });

  final List<int> attachmentIds;
  final List<int> transactionIds;
  final List<int> statementIds;
}

class _AttachmentSnapshot {
  const _AttachmentSnapshot({
    required this.attachmentId,
    required this.attachmentIds,
    required this.transactionIds,
    required this.statementIds,
  });

  final int attachmentId;
  final List<int> attachmentIds;
  final List<int> transactionIds;
  final List<int> statementIds;

  int get attachmentCount => attachmentIds.length;
  int get transactionCount => transactionIds.length;
  int get statementCount => statementIds.length;
}
