import 'dart:async';
import 'dart:io';

import 'package:firebirdpod/firebirdpod.dart';
import 'package:serverpod_database/serverpod_database.dart';
import 'package:test/test.dart';

import 'firebird_test_support.dart';

const _tableName = 'FIREBIRDPOD_SERVERPOD_READ';

class _ReadRow implements TableRow<int?> {
  _ReadRow({
    required this.id,
    required this.name,
    required this.flag,
    required this.note,
    required this.createdAt,
  });

  factory _ReadRow.fromJson(Map<String, dynamic> json) {
    final createdAt = json['createdAt'];
    return _ReadRow(
      id: json['id'] as int?,
      name: json['name'] as String,
      flag: json['flag'] as bool,
      note: json['note'] as String?,
      createdAt: createdAt is DateTime
          ? createdAt
          : DateTime.parse(createdAt as String),
    );
  }

  static final _ReadTable _table = _ReadTable();

  @override
  final int? id;

  final String name;
  final bool flag;
  final String? note;
  final DateTime createdAt;

  @override
  _ReadTable get table => _table;

  @override
  Map<String, dynamic> toJson() => {
    'id': id,
    'name': name,
    'flag': flag,
    'note': note,
    'createdAt': createdAt,
  };
}

class _ReadTable extends Table<int?> {
  _ReadTable() : super(tableName: _tableName);

  late final ColumnString name = ColumnString('name', this);
  late final ColumnBool flag = ColumnBool('flag', this);
  late final ColumnString note = ColumnString('note', this);
  late final ColumnDateTime createdAt = ColumnDateTime(
    'created_at',
    this,
    fieldName: 'createdAt',
  );

  @override
  List<Column> get columns => [id, name, flag, note, createdAt];
}

class _ReadSerializationManager extends SerializationManagerServer {
  final _ReadTable table = _ReadRow._table;

  @override
  T deserialize<T>(dynamic data, [Type? t]) {
    t ??= T;
    if (t == _ReadRow) {
      return _ReadRow.fromJson(Map<String, dynamic>.from(data)) as T;
    }
    return super.deserialize<T>(data, t);
  }

  @override
  String getModuleName() => 'test';

  @override
  Table? getTableForType(Type t) => t == _ReadRow ? table : null;

  @override
  List<TableDefinition> getTargetTableDefinitions() => const [];
}

class _TestDatabaseSession implements DatabaseSession {
  @override
  Transaction? transaction;

  @override
  Database get db => throw UnimplementedError('Database wrapper not needed.');

  @override
  LogQueryFunction? get logQuery => null;

  @override
  LogWarningFunction? get logWarning => null;
}

class _UnsupportedInclude implements IncludeObject {
  @override
  Map<String, Include?> get includes => const {};

  @override
  Table get table => _ReadRow._table;
}

void main() {
  group('Phase 02 Serverpod generated read bridge', () {
    late FirebirdServerpodDatabaseConnection connection;
    final table = _ReadRow._table;

    setUpAll(() async {
      registerFirebirdServerpodDialect();

      connection = _buildConnection();

      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      await connection.simpleExecute(
        session,
        '''
        recreate table $_tableName (
          ID integer generated by default as identity primary key,
          NAME varchar(60) not null,
          FLAG boolean not null,
          NOTE varchar(120),
          CREATED_AT timestamp not null
        )
        ''',
      );
    });

    tearDownAll(() async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      try {
        await connection.simpleExecute(
          session,
          'drop table $_tableName',
        );
      } catch (_) {}
    });

    setUp(() async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      await connection.simpleExecute(session, 'delete from $_tableName');
      await connection.simpleExecute(
        session,
        'alter table $_tableName alter ID restart with 1',
      );
      await _seedRows(connection);
    });

    test('find deserializes filtered, ordered, and paged rows', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      final rows = await connection.find<_ReadRow>(
        session,
        where: table.flag.equals(true),
        orderBy: table.createdAt,
        limit: 1,
        offset: 1,
      );

      expect(rows, hasLength(1));
      expect(rows.single.id, 3);
      expect(rows.single.name, 'charlie');
      expect(rows.single.flag, isTrue);
      expect(rows.single.note, 'note-c');
      expect(rows.single.createdAt, DateTime.parse('2026-04-15 10:00:00'));
    });

    test('find supports offset without limit on Firebird-native pagination', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      final rows = await connection.find<_ReadRow>(
        session,
        orderBy: table.id,
        offset: 2,
      );

      expect(rows.map((row) => row.id), [3, 4]);
    });

    test('findFirstRow and findById materialize mapped nullable fields', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();

      final newest = await connection.findFirstRow<_ReadRow>(
        session,
        orderBy: table.createdAt.desc(),
      );
      expect(newest?.name, 'delta');
      expect(newest?.note, 'note-d');

      final byId = await connection.findById<_ReadRow>(session, 1);
      expect(byId?.name, 'alpha');
      expect(byId?.note, isNull);
      expect(byId?.createdAt, DateTime.parse('2026-04-15 08:00:00'));

      final missing = await connection.findById<_ReadRow>(session, 999);
      expect(missing, isNull);
    });

    test('count supports filters and limit-wrapped counting', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();

      expect(await connection.count<_ReadRow>(session), 4);
      expect(
        await connection.count<_ReadRow>(
          session,
          where: table.flag.equals(true),
        ),
        3,
      );
      expect(
        await connection.count<_ReadRow>(
          session,
          where: table.flag.equals(true),
          limit: 2,
        ),
        2,
      );
    });

    test('find supports Firebird FOR UPDATE locking inside explicit transactions', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();

      await connection.transaction<void>(
        (transaction) async {
          final rows = await connection.find<_ReadRow>(
            session,
            where: table.id.equals(2),
            transaction: transaction,
            lockMode: LockMode.forUpdate,
          );

          expect(rows, hasLength(1));
          expect(rows.single.name, 'bravo');
        },
        settings: const TransactionSettings(),
        session: session,
      );
    });

    test('find rejects includes until relation loading lands', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();

      await expectLater(
        () => connection.find<_ReadRow>(
          session,
          include: _UnsupportedInclude(),
        ),
        throwsA(
          isA<UnsupportedError>().having(
            (error) => error.message,
            'message',
            contains('includes'),
          ),
        ),
      );
    });
  });
}

FirebirdServerpodDatabaseConnection _buildConnection() {
  final provider = DatabaseProvider.forDialect(DatabaseDialect.firebird)
      as FirebirdServerpodDatabaseProvider;
  final poolManager = provider.createPoolManager(
    _ReadSerializationManager(),
    null,
    FirebirdServerpodDatabaseConfig(
      host: Platform.environment['FIREBIRDPOD_TEST_HOST'] ?? 'localhost',
      port: _testPort(),
      user: firebirdTestUser(),
      password: firebirdTestPassword(),
      name: firebirdTestDatabasePath(),
      fbClientLibraryPath: firebirdClientLibraryPath(),
    ),
  );
  return provider.createConnection(poolManager);
}

Future<void> _seedRows(FirebirdServerpodDatabaseConnection connection) async {
  final session = _TestDatabaseSession();
  final inserts = <String>[
    "insert into $_tableName (NAME, FLAG, NOTE, CREATED_AT) values ('alpha', TRUE, NULL, '2026-04-15 08:00:00')",
    "insert into $_tableName (NAME, FLAG, NOTE, CREATED_AT) values ('bravo', FALSE, 'note-b', '2026-04-15 09:00:00')",
    "insert into $_tableName (NAME, FLAG, NOTE, CREATED_AT) values ('charlie', TRUE, 'note-c', '2026-04-15 10:00:00')",
    "insert into $_tableName (NAME, FLAG, NOTE, CREATED_AT) values ('delta', TRUE, 'note-d', '2026-04-15 11:00:00')",
  ];

  for (final sql in inserts) {
    await connection.simpleExecute(session, sql);
  }
}

int _testPort() {
  final value = Platform.environment['FIREBIRDPOD_TEST_PORT'];
  if (value == null || value.isEmpty) return 3050;
  return int.parse(value);
}
