import 'dart:async';
import 'dart:io';

import 'package:firebirdpod/firebirdpod.dart';
import 'package:serverpod_database/serverpod_database.dart';
import 'package:test/test.dart';

import 'firebird_test_support.dart';

const _tableName = 'FIREBIRDPOD_SERVERPOD_RAW';

class _TestSerializationManager extends SerializationManagerServer {
  @override
  String getModuleName() => 'test';

  @override
  Table? getTableForType(Type t) => null;

  @override
  List<TableDefinition> getTargetTableDefinitions() => const [];
}

class _LoggedQuery {
  _LoggedQuery({
    required this.query,
    required this.duration,
    required this.numRowsAffected,
    required this.error,
  });

  final String query;
  final Duration duration;
  final int? numRowsAffected;
  final String? error;
}

class _TestDatabaseSession implements DatabaseSession {
  final List<_LoggedQuery> queries = <_LoggedQuery>[];
  final List<String> warnings = <String>[];

  @override
  Transaction? transaction;

  @override
  Database get db => throw UnimplementedError('Database wrapper not needed.');

  @override
  LogQueryFunction? get logQuery => ({
    required String query,
    required Duration duration,
    required int? numRowsAffected,
    required String? error,
    required StackTrace stackTrace,
  }) async {
    queries.add(
      _LoggedQuery(
        query: query,
        duration: duration,
        numRowsAffected: numRowsAffected,
        error: error,
      ),
    );
  };

  @override
  LogWarningFunction? get logWarning => (message) async {
    warnings.add(message);
  };
}

void main() {
  group('Phase 02 Serverpod raw bridge', () {
    late FirebirdServerpodDatabaseConnection connection;

    setUpAll(() async {
      registerFirebirdServerpodDialect();

      connection = _buildConnection();

      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      await connection.simpleExecute(
        session,
        '''
        recreate table $_tableName (
          ID integer generated by default as identity primary key,
          NAME varchar(60) not null,
          FLAG boolean,
          NOTE varchar(120)
        )
        ''',
      );
    });

    tearDownAll(() async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      try {
        await connection.simpleExecute(
          session,
          'drop table $_tableName',
        );
      } catch (_) {}
    });

    setUp(() async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      await connection.simpleExecute(session, 'delete from $_tableName');
      await connection.simpleExecute(
        session,
        'alter table $_tableName alter ID restart with 1',
      );
    });

    test('query supports named parameters and exposes schema and column maps', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();
      final result = await connection.query(
        session,
        '''
        select
          cast(@name as varchar(30)) as NAME,
          cast(@note as varchar(30)) as NOTE_VALUE
        from rdb\$database
        ''',
        parameters: QueryParameters.named({
          'name': 'alpha',
          'note': 'first',
        }),
      );

      expect(result, hasLength(1));
      expect(
        result.schema.columns.map((column) => column.columnName).toList(),
        ['NAME', 'NOTE_VALUE'],
      );
      expect(
        result.single.toColumnMap(),
        {'NAME': 'alpha', 'NOTE_VALUE': 'first'},
      );
      expect(session.queries, hasLength(1));
      expect(session.queries.single.error, isNull);
      expect(session.queries.single.numRowsAffected, 1);
    });

    test('execute and simpleExecute return affected row counts', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();

      final inserted = await connection.execute(
        session,
        'insert into $_tableName (NAME, FLAG, NOTE) values (\$1, \$2, \$3)',
        parameters: QueryParameters.positional(['bravo', true, 'hello']),
      );
      expect(inserted, 1);

      final updated = await connection.simpleExecute(
        session,
        "update $_tableName set NOTE = 'updated' where NAME = 'bravo'",
      );
      expect(updated, 1);

      final rows = await connection.query(
        session,
        'select NAME, FLAG, NOTE from $_tableName',
      );
      expect(
        rows.single.toColumnMap(),
        {'NAME': 'bravo', 'FLAG': true, 'NOTE': 'updated'},
      );
    });

    test('transaction commits on success and keeps raw queries on the same attachment', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();

      final result = await connection.transaction<String>(
        (transaction) async {
          final insertCount = await connection.execute(
            session,
            'insert into $_tableName (NAME, FLAG) values (\$1, \$2)',
            transaction: transaction,
            parameters: QueryParameters.positional(['committed', true]),
          );
          expect(insertCount, 1);

          final rows = await connection.query(
            session,
            'select count(*) as TOTAL_ROWS from $_tableName',
            transaction: transaction,
          );
          expect(rows.single.toColumnMap()['TOTAL_ROWS'], 1);

          return 'committed';
        },
        settings: const TransactionSettings(
          isolationLevel: IsolationLevel.repeatableRead,
        ),
        session: session,
      );

      expect(result, 'committed');
      expect(await _rowCount(connection), 1);
    });

    test('transaction rolls back on exception', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();

      await expectLater(
        () => connection.transaction<void>(
          (transaction) async {
            await connection.execute(
              session,
              'insert into $_tableName (NAME) values (\$1)',
              transaction: transaction,
              parameters: QueryParameters.positional(['rolled-back']),
            );
            throw StateError('fail inside transaction');
          },
          settings: const TransactionSettings(),
          session: session,
        ),
        throwsA(isA<StateError>()),
      );

      expect(await _rowCount(connection), 0);
    });

    test('transaction cancel discards work and still returns the closure result', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();

      final result = await connection.transaction<String>(
        (transaction) async {
          await connection.execute(
            session,
            'insert into $_tableName (NAME) values (\$1)',
            transaction: transaction,
            parameters: QueryParameters.positional(['cancelled']),
          );
          await transaction.cancel();
          return 'cancelled';
        },
        settings: const TransactionSettings(),
        session: session,
      );

      expect(result, 'cancelled');
      expect(await _rowCount(connection), 0);
    });

    test('transaction runtime parameters map into Firebird USER_TRANSACTION context', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();

      await connection.transaction<void>(
        (transaction) async {
          await transaction.setRuntimeParameters((_) {
            return [
              MapRuntimeParameters({
                'REQUEST_ID': 'req-42',
                'TENANT_ID': 77,
                'TRACE_ENABLED': true,
              }),
            ];
          });

          expect(
            transaction.runtimeParameters,
            containsPair('REQUEST_ID', 'req-42'),
          );
          expect(
            transaction.runtimeParameters,
            containsPair('TENANT_ID', 77),
          );

          final requestId = await connection.query(
            session,
            '''
            select rdb\$get_context('USER_TRANSACTION', \$1) as CTX_VALUE
            from rdb\$database
            ''',
            transaction: transaction,
            parameters: QueryParameters.positional(['REQUEST_ID']),
          );

          final tenantId = await connection.query(
            session,
            '''
            select rdb\$get_context('USER_TRANSACTION', \$1) as CTX_VALUE
            from rdb\$database
            ''',
            transaction: transaction,
            parameters: QueryParameters.positional(['TENANT_ID']),
          );

          expect(requestId.single.toColumnMap()['CTX_VALUE'], 'req-42');
          expect(tenantId.single.toColumnMap()['CTX_VALUE'], '77');
        },
        settings: const TransactionSettings(),
        session: session,
      );
    });

    test('transaction rejects PostgreSQL-specific runtime parameter groups clearly', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();

      await expectLater(
        () => connection.transaction<void>(
          (transaction) async {
            await transaction.setRuntimeParameters(
              (params) => [params.searchPaths(['app'])],
            );
          },
          settings: const TransactionSettings(),
          session: session,
        ),
        throwsA(
          isA<UnsupportedError>().having(
            (error) => error.message,
            'message',
            contains('search_path'),
          ),
        ),
      );
    });

    test('query logging records errors from failed statements', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final session = _TestDatabaseSession();

      await expectLater(
        () => connection.query(
          session,
          'select definitely_missing_column from rdb\$database',
        ),
        throwsA(isA<Exception>()),
      );

      expect(session.queries, hasLength(1));
      expect(session.queries.single.error, isNotNull);
      expect(session.queries.single.query, contains('definitely_missing_column'));
    });
  });
}

FirebirdServerpodDatabaseConnection _buildConnection() {
  final provider = DatabaseProvider.forDialect(DatabaseDialect.firebird)
      as FirebirdServerpodDatabaseProvider;
  final poolManager = provider.createPoolManager(
    _TestSerializationManager(),
    null,
    FirebirdServerpodDatabaseConfig(
      host: Platform.environment['FIREBIRDPOD_TEST_HOST'] ?? 'localhost',
      port: _testPort(),
      user: firebirdTestUser(),
      password: firebirdTestPassword(),
      name: firebirdTestDatabasePath(),
      fbClientLibraryPath: firebirdClientLibraryPath(),
    ),
  );
  return provider.createConnection(poolManager);
}

Future<int> _rowCount(FirebirdServerpodDatabaseConnection connection) async {
  final session = _TestDatabaseSession();
  final rows = await connection.query(
    session,
    'select count(*) as TOTAL_ROWS from $_tableName',
  );
  return rows.single.toColumnMap()['TOTAL_ROWS'] as int;
}

int _testPort() {
  final value = Platform.environment['FIREBIRDPOD_TEST_PORT'];
  if (value == null || value.isEmpty) return 3050;
  return int.parse(value);
}
