import 'dart:typed_data';

import 'package:firebirdpod/firebirdpod.dart';
import 'package:test/test.dart';

import 'firebird_test_support.dart';

const _parentTable = 'FIREBIRDPOD_WRITE_PARENT';
const _childTable = 'FIREBIRDPOD_WRITE_CHILD';

void main() {
  group('Phase 01 direct fbclient write contract', () {
    setUpAll(() async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await _openConnection();
      try {
        await _dropTableIfExists(connection, _childTable);
        await _dropTableIfExists(connection, _parentTable);

        await connection.execute('''
          create table $_parentTable (
            ID bigint generated by default as identity primary key,
            NAME varchar(40) not null unique,
            STATUS varchar(12) not null,
            SCORE integer not null,
            constraint CK_FPD_WRITE_PARENT_SCORE check (SCORE >= 0)
          )
        ''');

        await connection.execute('''
          create table $_childTable (
            ID bigint generated by default as identity primary key,
            PARENT_ID bigint not null,
            LABEL varchar(40) not null,
            PAYLOAD blob sub_type binary,
            constraint FK_FPD_WRITE_CHILD_PARENT
              foreign key (PARENT_ID) references $_parentTable (ID)
          )
        ''');
      } finally {
        await connection.close();
      }
    });

    tearDownAll(() async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await _openConnection();
      try {
        await _dropTableIfExists(connection, _childTable);
        await _dropTableIfExists(connection, _parentTable);
      } finally {
        await connection.close();
      }
    });

    setUp(() async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await _openConnection();
      try {
        await connection.execute('delete from $_childTable');
        await connection.execute('delete from $_parentTable');
        await connection.execute(
          'alter table $_childTable alter ID restart with 1',
        );
        await connection.execute(
          'alter table $_parentTable alter ID restart with 1',
        );
      } finally {
        await connection.close();
      }
    });

    test(
      'retained writes report generated ids and affected row counts',
      () async {
        if (!shouldRunDirectIntegrationTests()) {
          return;
        }

        final connection = await _openConnection();
        addTearDown(connection.close);

        final insertResult = await _insertParent(
          connection,
          name: 'alpha',
          status: 'ACTIVE',
          score: 10,
        );
        expect(insertResult.generatedId(), 1);
        expect(insertResult.singleRow?['ID'], 1);
        expect(insertResult.affectedRows, 1);

        final updateResult = await connection.execute('''
        update $_parentTable
        set score = \$1
        where id = \$2
        ''', parameters: FirebirdStatementParameters.positional([25, 1]));
        expect(updateResult.affectedRows, 1);

        final deleteResult = await connection.execute('''
        delete from $_parentTable
        where id = \$1
        ''', parameters: FirebirdStatementParameters.positional([1]));
        expect(deleteResult.affectedRows, 1);

        final missingDeleteResult = await connection.execute('''
        delete from $_parentTable
        where id = \$1
        ''', parameters: FirebirdStatementParameters.positional([999]));
        expect(missingDeleteResult.affectedRows, 0);
      },
    );

    test('retained delete reports multi-row counts correctly', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await _openConnection();
      addTearDown(connection.close);

      await _insertParent(
        connection,
        name: 'alpha',
        status: 'ACTIVE',
        score: 10,
      );
      await _insertParent(
        connection,
        name: 'bravo',
        status: 'INACTIVE',
        score: 20,
      );
      await _insertParent(
        connection,
        name: 'charlie',
        status: 'INACTIVE',
        score: 30,
      );

      final deleteResult = await connection.execute('''
        delete from $_parentTable
        where status = \$1
        ''', parameters: FirebirdStatementParameters.positional(['INACTIVE']));
      expect(deleteResult.affectedRows, 2);
      expect(await _countRows(connection, _parentTable), 1);
    });

    test(
      'update returning materializes multiple returned rows on the retained path',
      () async {
        if (!shouldRunDirectIntegrationTests()) {
          return;
        }

        final connection = await _openConnection();
        addTearDown(connection.close);

        await _insertParent(
          connection,
          name: 'alpha',
          status: 'ACTIVE',
          score: 10,
        );
        await _insertParent(
          connection,
          name: 'bravo',
          status: 'ACTIVE',
          score: 20,
        );
        await _insertParent(
          connection,
          name: 'charlie',
          status: 'ACTIVE',
          score: 30,
        );

        final result = await connection.execute(
          '''
          update $_parentTable
          set status = \$1
          where score >= \$2
          returning id, name, status
          ''',
          parameters: FirebirdStatementParameters.positional(['ARCHIVED', 20]),
        );

        final rows = result.rows.toList()
          ..sort(
            (left, right) => (left['ID'] as int).compareTo(right['ID'] as int),
          );
        expect(rows, hasLength(2));
        expect(rows[0], containsPair('ID', 2));
        expect(rows[0], containsPair('NAME', 'bravo'));
        expect(rows[0], containsPair('STATUS', 'ARCHIVED'));
        expect(rows[1], containsPair('ID', 3));
        expect(rows[1], containsPair('NAME', 'charlie'));
        expect(rows[1], containsPair('STATUS', 'ARCHIVED'));

        final archivedCount = await _selectScalar(
          connection,
          '''
          select count(*) as RESULT_VALUE
          from $_parentTable
          where status = \$1
          ''',
          ['ARCHIVED'],
        );
        expect(archivedCount, 2);
      },
    );

    test(
      'delete returning materializes multiple returned rows on the retained path',
      () async {
        if (!shouldRunDirectIntegrationTests()) {
          return;
        }

        final connection = await _openConnection();
        addTearDown(connection.close);

        await _insertParent(
          connection,
          name: 'alpha',
          status: 'ACTIVE',
          score: 10,
        );
        await _insertParent(
          connection,
          name: 'bravo',
          status: 'INACTIVE',
          score: 20,
        );
        await _insertParent(
          connection,
          name: 'charlie',
          status: 'INACTIVE',
          score: 30,
        );

        final result = await connection.execute(
          '''
          delete from $_parentTable
          where status = \$1
          returning id, name
          ''',
          parameters: FirebirdStatementParameters.positional(['INACTIVE']),
        );

        final rows = result.rows.toList()
          ..sort(
            (left, right) => (left['ID'] as int).compareTo(right['ID'] as int),
          );
        expect(rows, hasLength(2));
        expect(rows[0], containsPair('ID', 2));
        expect(rows[0], containsPair('NAME', 'bravo'));
        expect(rows[1], containsPair('ID', 3));
        expect(rows[1], containsPair('NAME', 'charlie'));
        expect(await _countRows(connection, _parentTable), 1);
      },
    );

    test(
      'update or insert returning supports Firebird-native upsert semantics',
      () async {
        if (!shouldRunDirectIntegrationTests()) {
          return;
        }

        final connection = await _openConnection();
        addTearDown(connection.close);

        final firstInsert = await connection.execute(
          '''
          update or insert into $_parentTable (NAME, STATUS, SCORE)
          values (\$1, \$2, \$3)
          matching (NAME)
          returning id, name, status, score
          ''',
          parameters: FirebirdStatementParameters.positional([
            'alpha',
            'ACTIVE',
            10,
          ]),
        );
        expect(firstInsert.singleRow?['ID'], 1);
        expect(firstInsert.singleRow?['NAME'], 'alpha');
        expect(firstInsert.singleRow?['STATUS'], 'ACTIVE');
        expect(firstInsert.singleRow?['SCORE'], 10);

        final updateExisting = await connection.execute(
          '''
          update or insert into $_parentTable (NAME, STATUS, SCORE)
          values (\$1, \$2, \$3)
          matching (NAME)
          returning id, name, status, score
          ''',
          parameters: FirebirdStatementParameters.positional([
            'alpha',
            'ARCHIVED',
            99,
          ]),
        );
        expect(updateExisting.singleRow?['ID'], 1);
        expect(updateExisting.singleRow?['NAME'], 'alpha');
        expect(updateExisting.singleRow?['STATUS'], 'ARCHIVED');
        expect(updateExisting.singleRow?['SCORE'], 99);

        final secondInsert = await connection.execute(
          '''
          update or insert into $_parentTable (NAME, STATUS, SCORE)
          values (\$1, \$2, \$3)
          matching (NAME)
          returning id, name, status, score
          ''',
          parameters: FirebirdStatementParameters.positional([
            'bravo',
            'ACTIVE',
            20,
          ]),
        );
        expect(secondInsert.singleRow?['ID'], 2);
        expect(secondInsert.singleRow?['NAME'], 'bravo');

        final rows = await _selectAllRows(connection, '''
          select id, name, status, score
          from $_parentTable
          order by id
          ''');
        expect(rows, hasLength(2));
        expect(rows[0], containsPair('ID', 1));
        expect(rows[0], containsPair('STATUS', 'ARCHIVED'));
        expect(rows[0], containsPair('SCORE', 99));
        expect(rows[1], containsPair('ID', 2));
        expect(rows[1], containsPair('NAME', 'bravo'));
      },
    );

    test('explicit transaction rollback restores deleted rows', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await _openConnection();
      addTearDown(connection.close);

      final parentId = _generatedIdAsInt(
        await _insertParent(
          connection,
          name: 'alpha',
          status: 'ACTIVE',
          score: 10,
        ),
      );
      await _insertChild(
        connection,
        parentId: parentId,
        label: 'payload-a',
        payload: Uint8List.fromList([1, 2, 3]),
      );

      final transaction = await connection.beginTransaction();
      addTearDown(transaction.close);

      final childDelete = await transaction.execute('''
        delete from $_childTable
        where parent_id = \$1
        ''', parameters: FirebirdStatementParameters.positional([parentId]));
      expect(childDelete.affectedRows, 1);

      final parentDelete = await transaction.execute('''
        delete from $_parentTable
        where id = \$1
        ''', parameters: FirebirdStatementParameters.positional([parentId]));
      expect(parentDelete.affectedRows, 1);

      expect(await _countRowsInTransaction(transaction, _childTable), 0);
      expect(await _countRowsInTransaction(transaction, _parentTable), 0);

      await transaction.rollback();

      expect(await _countRows(connection, _childTable), 1);
      expect(await _countRows(connection, _parentTable), 1);
    });

    test('explicit transaction commit persists updates and deletes', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await _openConnection();
      addTearDown(connection.close);

      final parentId = _generatedIdAsInt(
        await _insertParent(
          connection,
          name: 'alpha',
          status: 'ACTIVE',
          score: 10,
        ),
      );
      final childId = _generatedIdAsInt(
        await _insertChild(
          connection,
          parentId: parentId,
          label: 'payload-a',
          payload: Uint8List.fromList([1, 2, 3]),
        ),
      );

      final transaction = await connection.beginTransaction();
      addTearDown(transaction.close);

      final updateResult = await transaction.execute(
        '''
        update $_parentTable
        set score = \$1
        where id = \$2
        ''',
        parameters: FirebirdStatementParameters.positional([77, parentId]),
      );
      expect(updateResult.affectedRows, 1);

      final deleteResult = await transaction.execute('''
        delete from $_childTable
        where id = \$1
        ''', parameters: FirebirdStatementParameters.positional([childId]));
      expect(deleteResult.affectedRows, 1);

      await transaction.commit();

      final parentRow = await _selectSingleRow(
        connection,
        '''
        select score
        from $_parentTable
        where id = \$1
        ''',
        [parentId],
      );
      expect(parentRow['SCORE'], 77);
      expect(await _countRows(connection, _childTable), 0);
    });

    test('client-side binding rejects null for non-null fields', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await _openConnection();
      addTearDown(connection.close);

      await expectLater(
        () => connection.execute(
          '''
          insert into $_parentTable (NAME, STATUS, SCORE)
          values (\$1, \$2, \$3)
          ''',
          parameters: FirebirdStatementParameters.positional([
            null,
            'ACTIVE',
            1,
          ]),
        ),
        throwsArgumentError,
      );
    });

    test(
      'server-side write constraint failures surface as structured database exceptions',
      () async {
        if (!shouldRunDirectIntegrationTests()) {
          return;
        }

        final connection = await _openConnection();
        addTearDown(connection.close);

        await _insertParent(
          connection,
          name: 'alpha',
          status: 'ACTIVE',
          score: 10,
        );

        final uniqueError = await _captureDbException(() {
          return connection.execute(
            '''
          insert into $_parentTable (NAME, STATUS, SCORE)
          values (\$1, \$2, \$3)
          ''',
            parameters: FirebirdStatementParameters.positional([
              'alpha',
              'ACTIVE',
              11,
            ]),
          );
        });
        expect(uniqueError.operation, 'execute');
        expect(uniqueError.message, isNotEmpty);
        expect(uniqueError.primaryErrorCode, isNotNull);
        expect(uniqueError.errorCodes, isNotEmpty);

        final checkError = await _captureDbException(() {
          return connection.execute(
            '''
          insert into $_parentTable (NAME, STATUS, SCORE)
          values (\$1, \$2, \$3)
          ''',
            parameters: FirebirdStatementParameters.positional([
              'check-fail',
              'ACTIVE',
              -1,
            ]),
          );
        });
        expect(checkError.operation, 'execute');
        expect(checkError.message, isNotEmpty);
        expect(checkError.primaryErrorCode, isNotNull);

        final foreignKeyError = await _captureDbException(() {
          return connection.execute(
            '''
          insert into $_childTable (PARENT_ID, LABEL, PAYLOAD)
          values (\$1, \$2, \$3)
          ''',
            parameters: FirebirdStatementParameters.positional([
              999,
              'missing-parent',
              Uint8List.fromList([9]),
            ]),
          );
        });
        expect(foreignKeyError.operation, 'execute');
        expect(foreignKeyError.message, isNotEmpty);
        expect(foreignKeyError.primaryErrorCode, isNotNull);
      },
    );

    test('delete that violates foreign keys is mapped cleanly', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await _openConnection();
      addTearDown(connection.close);

      final parentId = _generatedIdAsInt(
        await _insertParent(
          connection,
          name: 'alpha',
          status: 'ACTIVE',
          score: 10,
        ),
      );
      await _insertChild(
        connection,
        parentId: parentId,
        label: 'payload-a',
        payload: Uint8List.fromList([1, 2, 3]),
      );

      final error = await _captureDbException(() {
        return connection.execute('''
          delete from $_parentTable
          where id = \$1
          ''', parameters: FirebirdStatementParameters.positional([parentId]));
      });
      expect(error.operation, 'execute');
      expect(error.message, isNotEmpty);
      expect(error.primaryErrorCode, isNotNull);
      expect(await _countRows(connection, _parentTable), 1);
    });

    test('blob payloads survive normal insert and update flows', () async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await _openConnection();
      addTearDown(connection.close);

      final parentId = _generatedIdAsInt(
        await _insertParent(
          connection,
          name: 'alpha',
          status: 'ACTIVE',
          score: 10,
        ),
      );
      final childId = _generatedIdAsInt(
        await _insertChild(
          connection,
          parentId: parentId,
          label: 'payload-a',
          payload: Uint8List.fromList([1, 2, 3]),
        ),
      );

      final updateResult = await connection.execute(
        '''
        update $_childTable
        set payload = \$1
        where id = \$2
        ''',
        parameters: FirebirdStatementParameters.positional([
          Uint8List.fromList([9, 8, 7, 6]),
          childId,
        ]),
      );
      expect(updateResult.affectedRows, 1);

      final childRow = await _selectSingleRow(
        connection,
        '''
        select payload
        from $_childTable
        where id = \$1
        ''',
        [childId],
      );
      expect(childRow['PAYLOAD'], Uint8List.fromList([9, 8, 7, 6]));
    });
  });
}

Future<FirebirdConnection> _openConnection() {
  return buildDirectEndpoint(database: firebirdTestDatabasePath()).connect();
}

Future<void> _dropTableIfExists(
  FirebirdConnection connection,
  String tableName,
) async {
  try {
    await connection.execute('drop table $tableName');
  } on FirebirdDatabaseException {
    // Ignore teardown/setup cleanup when the test table does not exist yet.
  }
}

Future<FirebirdExecutionResult> _insertParent(
  FirebirdConnection connection, {
  required String name,
  required String status,
  required int score,
}) {
  return connection.execute(
    '''
    insert into $_parentTable (NAME, STATUS, SCORE)
    values (\$1, \$2, \$3)
    returning ID
    ''',
    parameters: FirebirdStatementParameters.positional([name, status, score]),
  );
}

Future<FirebirdExecutionResult> _insertChild(
  FirebirdConnection connection, {
  required int parentId,
  required String label,
  Uint8List? payload,
}) {
  return connection.execute(
    '''
    insert into $_childTable (PARENT_ID, LABEL, PAYLOAD)
    values (\$1, \$2, \$3)
    returning ID
    ''',
    parameters: FirebirdStatementParameters.positional([
      parentId,
      label,
      payload,
    ]),
  );
}

int _generatedIdAsInt(FirebirdExecutionResult result) {
  final generatedId = result.generatedId();
  if (generatedId is int) {
    return generatedId;
  }
  throw StateError('Expected an integer generated id, got $generatedId.');
}

Future<int> _countRows(FirebirdConnection connection, String tableName) async {
  final row = await _selectSingleRow(
    connection,
    'select count(*) as RESULT_TOTAL from $tableName',
    const [],
  );
  return row['RESULT_TOTAL'] as int;
}

Future<List<Map<String, Object?>>> _selectAllRows(
  FirebirdConnection connection,
  String sql, [
  List<Object?> values = const <Object?>[],
]) async {
  final result = await connection.execute(
    sql,
    parameters: FirebirdStatementParameters.positional(values),
  );
  return result.rows;
}

Future<int> _countRowsInTransaction(
  FirebirdTransaction transaction,
  String tableName,
) async {
  final result = await transaction.execute(
    'select count(*) as RESULT_TOTAL from $tableName',
  );
  return result.singleRow!['RESULT_TOTAL'] as int;
}

Future<Map<String, Object?>> _selectSingleRow(
  FirebirdConnection connection,
  String sql,
  List<Object?> values,
) async {
  final result = await connection.execute(
    sql,
    parameters: FirebirdStatementParameters.positional(values),
  );
  return result.singleRow!;
}

Future<Object?> _selectScalar(
  FirebirdConnection connection,
  String sql, [
  List<Object?> values = const <Object?>[],
]) async {
  final row = await _selectSingleRow(connection, sql, values);
  return row.values.single;
}

Future<FirebirdDatabaseException> _captureDbException(
  Future<Object?> Function() action,
) async {
  try {
    await action();
  } on FirebirdDatabaseException catch (error) {
    return error;
  }

  fail('Expected FirebirdDatabaseException to be thrown.');
}
