import 'dart:async';
import 'dart:isolate';

import 'package:firebirdpod/firebirdpod.dart';
import 'package:serverpod_database/serverpod_database.dart';
import 'package:test/test.dart';

import 'firebird_test_support.dart';

void main() {
  group('Firebird Serverpod migration runner', () {
    late FirebirdServerpodPoolManager poolManager;
    late Database database;
    late _TestSession session;
    var isInitialized = false;

    const testTableName = 'firebirdpod_migration_runner_test';
    const lockTableName =
        FirebirdServerpodMigrationRunner.migrationLockTableName;

    setUpAll(() async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      registerFirebirdServerpodDialect();
      poolManager = FirebirdServerpodPoolManager(
        _TestSerializationManager(),
        null,
        FirebirdServerpodDatabaseConfig(
          host: 'localhost',
          port: 3050,
          user: firebirdTestUser(),
          password: firebirdTestPassword(),
          name: firebirdTestDatabasePath(),
          charset: 'UTF8',
          fbClientLibraryPath: firebirdClientLibraryPath(),
        ),
      )..start();

      session = _TestSession(() => database);
      database = DatabaseConstructor.create(
        session: session,
        poolManager: poolManager,
      );
      isInitialized = true;

      await _cleanupMigrationArtifacts(session);
    });

    tearDown(() async {
      if (!shouldRunDirectIntegrationTests()) return;
      await _dropTableIfExists(session, testTableName);
    });

    tearDownAll(() async {
      if (!shouldRunDirectIntegrationTests()) return;
      if (!isInitialized) {
        await poolManager.stop();
        return;
      }
      await _cleanupMigrationArtifacts(session);
      await poolManager.stop();
    });

    test(
      'runs migrations inside one explicit transaction and rolls back DDL on failure',
      () async {
        if (!shouldRunDirectIntegrationTests()) {
          markTestSkipped(
            'set FIREBIRDPOD_RUN_FBCLIENT_DIRECT=1 to run live Firebird migration tests',
          );
          return;
        }

        const runner = FirebirdServerpodMigrationRunner(runMode: 'development');

        await expectLater(
          runner.runMigrations(session, (transaction) async {
            expect(transaction, isNotNull);

            await session.db.unsafeSimpleExecute('''
create table "$testTableName" (
  "id" bigint generated by default as identity primary key,
  "name" varchar(50) character set utf8 not null
);
update "serverpod_migration_lock"
set "acquired_at" = current_timestamp
where "id" = 1;
''', transaction: transaction);

            throw StateError('force rollback');
          }),
          throwsA(isA<StateError>()),
        );

        expect(await _tableExists(session, testTableName), isFalse);
        expect(await _tableExists(session, lockTableName), isTrue);
      },
    );

    test(
      'serializes concurrent migration windows with a Firebird row lock',
      () async {
        if (!shouldRunDirectIntegrationTests()) {
          markTestSkipped(
            'set FIREBIRDPOD_RUN_FBCLIENT_DIRECT=1 to run live Firebird migration tests',
          );
          return;
        }

        const runner = FirebirdServerpodMigrationRunner(runMode: 'development');
        final firstEntered = Completer<void>();
        final releaseFirst = Completer<void>();
        final secondEntered = Completer<void>();
        final secondDone = Completer<void>();
        final secondMessages = ReceivePort();
        final secondErrors = ReceivePort();

        final firstFuture = runner.runMigrations(session, (transaction) async {
          expect(transaction, isNotNull);
          firstEntered.complete();
          await releaseFirst.future;
        });

        await firstEntered.future;

        final secondMessageSubscription = secondMessages.listen((message) {
          if (message == 'entered') {
            if (!secondEntered.isCompleted) {
              secondEntered.complete();
            }
          } else if (message == 'done') {
            if (!secondDone.isCompleted) {
              secondDone.complete();
            }
          } else if (message is Map<Object?, Object?>) {
            final error = message['error'];
            final stack = message['stack'];
            if (!secondDone.isCompleted) {
              secondDone.completeError(
                StateError('Isolate migration failed: $error\n$stack'),
              );
            }
          }
        });
        final secondErrorSubscription = secondErrors.listen((message) {
          if (!secondDone.isCompleted) {
            secondDone.completeError(
              StateError('Isolate migration error: $message'),
            );
          }
        });
        final isolate = await Isolate.spawn<_MigrationRunnerIsolateRequest>(
          _runMigrationWindowInIsolate,
          _MigrationRunnerIsolateRequest(secondMessages.sendPort),
          onError: secondErrors.sendPort,
        );

        await Future<void>.delayed(const Duration(milliseconds: 250));
        expect(secondEntered.isCompleted, isFalse);

        releaseFirst.complete();
        await firstFuture.timeout(const Duration(seconds: 5));
        await secondEntered.future.timeout(const Duration(seconds: 5));
        await secondDone.future.timeout(const Duration(seconds: 5));

        expect(secondEntered.isCompleted, isTrue);

        isolate.kill(priority: Isolate.immediate);
        await secondMessageSubscription.cancel();
        await secondErrorSubscription.cancel();
        secondMessages.close();
        secondErrors.close();
      },
    );
  });
}

class _MigrationRunnerIsolateRequest {
  const _MigrationRunnerIsolateRequest(this.sendPort);

  final SendPort sendPort;
}

Future<void> _runMigrationWindowInIsolate(
  _MigrationRunnerIsolateRequest request,
) async {
  registerFirebirdServerpodDialect();
  final poolManager = FirebirdServerpodPoolManager(
    _TestSerializationManager(),
    null,
    FirebirdServerpodDatabaseConfig(
      host: 'localhost',
      port: 3050,
      user: firebirdTestUser(),
      password: firebirdTestPassword(),
      name: firebirdTestDatabasePath(),
      charset: 'UTF8',
      fbClientLibraryPath: firebirdClientLibraryPath(),
    ),
  )..start();

  late Database database;
  final session = _TestSession(() => database);
  database = DatabaseConstructor.create(
    session: session,
    poolManager: poolManager,
  );

  try {
    const runner = FirebirdServerpodMigrationRunner(runMode: 'development');
    await runner.runMigrations(session, (transaction) async {
      request.sendPort.send('entered');
    });
    request.sendPort.send('done');
  } catch (error, stackTrace) {
    request.sendPort.send({
      'error': error.toString(),
      'stack': stackTrace.toString(),
    });
  } finally {
    await poolManager.stop();
  }
}

Future<void> _cleanupMigrationArtifacts(DatabaseSession session) async {
  await _dropTableIfExists(
    session,
    FirebirdServerpodMigrationRunner.migrationLockTableName,
  );
  await _dropTableIfExists(session, 'firebirdpod_migration_runner_test');
}

Future<bool> _tableExists(DatabaseSession session, String tableName) async {
  return await _lookupStoredTableName(session, tableName) != null;
}

Future<String?> _lookupStoredTableName(
  DatabaseSession session,
  String tableName,
) async {
  final result = await session.db.unsafeQuery('''
select trim(rdb\$relation_name) as "TABLE_NAME"
from rdb\$relations
where upper(rdb\$relation_name) = '${tableName.toUpperCase()}'
  and coalesce(rdb\$system_flag, 0) = 0
''');

  if (result.isEmpty) {
    return null;
  }

  final value = result.first.toColumnMap()['TABLE_NAME'];
  if (value == null) {
    return null;
  }

  return value.toString();
}

Future<void> _dropTableIfExists(
  DatabaseSession session,
  String tableName,
) async {
  final storedName = await _lookupStoredTableName(session, tableName);
  if (storedName == null) {
    return;
  }

  await session.db.unsafeExecute('drop table "$storedName"');
}

class _TestSerializationManager extends SerializationManagerServer {
  @override
  String getModuleName() => 'test';

  @override
  Table? getTableForType(Type t) => null;

  @override
  List<TableDefinition> getTargetTableDefinitions() => const [];
}

class _TestSession implements DatabaseSession {
  _TestSession(this._database);

  final Database Function() _database;

  @override
  Database get db => _database();

  @override
  Transaction? get transaction => null;

  @override
  LogQueryFunction? get logQuery => null;

  @override
  LogWarningFunction? get logWarning => null;
}
