import 'package:firebirdpod/firebirdpod.dart';
import 'package:serverpod_database/serverpod_database.dart';
import 'package:test/test.dart';

void main() {
  const generator = FirebirdServerpodSqlGenerator();

  group('Firebird Serverpod SQL generator', () {
    test('generates deterministic Firebird definition SQL', () {
      final databaseDefinition = DatabaseDefinition(
        moduleName: 'app',
        tables: [
          TableDefinition(
            name: 'parent',
            dartName: 'Parent',
            schema: 'public',
            columns: [
              ColumnDefinition(
                name: 'id',
                columnType: ColumnType.bigint,
                isNullable: false,
                columnDefault: defaultIntSerial,
              ),
              ColumnDefinition(
                name: 'name',
                columnType: ColumnType.text,
                isNullable: false,
              ),
              ColumnDefinition(
                name: 'isActive',
                columnType: ColumnType.boolean,
                isNullable: false,
                columnDefault: defaultBooleanTrue,
              ),
              ColumnDefinition(
                name: 'createdAt',
                columnType: ColumnType.timestampWithoutTimeZone,
                isNullable: false,
                columnDefault: defaultDateTimeValueNow,
              ),
              ColumnDefinition(
                name: 'publicId',
                columnType: ColumnType.uuid,
                isNullable: false,
              ),
            ],
            foreignKeys: const [],
            indexes: [
              IndexDefinition(
                indexName: 'parent_pkey',
                elements: [
                  IndexElementDefinition(
                    type: IndexElementDefinitionType.column,
                    definition: 'id',
                  ),
                ],
                type: 'btree',
                isUnique: true,
                isPrimary: true,
              ),
              IndexDefinition(
                indexName: 'parent_public_id_idx',
                elements: [
                  IndexElementDefinition(
                    type: IndexElementDefinitionType.column,
                    definition: 'publicId',
                  ),
                ],
                type: 'btree',
                isUnique: true,
                isPrimary: false,
              ),
            ],
          ),
          TableDefinition(
            name: 'child',
            dartName: 'Child',
            schema: 'public',
            columns: [
              ColumnDefinition(
                name: 'id',
                columnType: ColumnType.bigint,
                isNullable: false,
                columnDefault: defaultIntSerial,
              ),
              ColumnDefinition(
                name: 'parentId',
                columnType: ColumnType.bigint,
                isNullable: false,
              ),
              ColumnDefinition(
                name: 'payload',
                columnType: ColumnType.json,
                isNullable: true,
              ),
            ],
            foreignKeys: [
              ForeignKeyDefinition(
                constraintName: 'child_parent_fk',
                columns: const ['parentId'],
                referenceTable: 'parent',
                referenceTableSchema: 'public',
                referenceColumns: const ['id'],
                onDelete: ForeignKeyAction.cascade,
              ),
            ],
            indexes: const [],
          ),
        ],
        installedModules: const [],
        migrationApiVersion: 1,
      );

      final sql = generator.generateDatabaseDefinitionSql(
        databaseDefinition,
        installedModules: [
          DatabaseMigrationVersionModel(
            module: 'app',
            version: '202604160001',
            timestamp: DateTime.utc(2026, 4, 16, 1, 2, 3, 456),
          ),
        ],
      );

      expect(
        sql,
        equals('''
--
-- Class Parent as table parent
--
CREATE TABLE "PARENT" (
  "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NAME" BLOB SUB_TYPE TEXT CHARACTER SET UTF8 NOT NULL,
  "ISACTIVE" BOOLEAN DEFAULT TRUE NOT NULL,
  "CREATEDAT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "PUBLICID" CHAR(36) CHARACTER SET ASCII NOT NULL
);

--
-- Class Child as table child
--
CREATE TABLE "CHILD" (
  "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PARENTID" BIGINT NOT NULL,
  "PAYLOAD" BLOB SUB_TYPE TEXT CHARACTER SET UTF8
);

ALTER TABLE "CHILD" ADD CONSTRAINT "CHILD_PARENT_FK" FOREIGN KEY ("PARENTID") REFERENCES "PARENT" ("ID") ON DELETE CASCADE;

CREATE UNIQUE INDEX "PARENT_PUBLIC_ID_IDX" ON "PARENT" ("PUBLICID");

UPDATE OR INSERT INTO "SERVERPOD_MIGRATIONS" ("MODULE", "VERSION", "TIMESTAMP") VALUES ('app', '202604160001', TIMESTAMP '2026-04-16 01:02:03.456') MATCHING ("MODULE");
'''),
      );
    });

    test('wraps create table if not exists in Firebird execute block', () {
      final databaseMigration = DatabaseMigration(
        actions: [
          DatabaseMigrationAction(
            type: DatabaseMigrationActionType.createTableIfNotExists,
            createTable: TableDefinition(
              name: 'audit_log',
              dartName: 'AuditLog',
              schema: 'public',
              columns: [
                ColumnDefinition(
                  name: 'id',
                  columnType: ColumnType.bigint,
                  isNullable: false,
                  columnDefault: defaultIntSerial,
                ),
                ColumnDefinition(
                  name: 'event',
                  columnType: ColumnType.text,
                  isNullable: false,
                ),
              ],
              foreignKeys: const [],
              indexes: [
                IndexDefinition(
                  indexName: 'audit_log_event_idx',
                  elements: [
                    IndexElementDefinition(
                      type: IndexElementDefinitionType.column,
                      definition: 'event',
                    ),
                  ],
                  type: 'btree',
                  isUnique: false,
                  isPrimary: false,
                ),
              ],
            ),
          ),
        ],
        warnings: const [],
        migrationApiVersion: 1,
      );

      final sql = generator.generateDatabaseMigrationSql(
        databaseMigration,
        DatabaseDefinition(
          moduleName: 'app',
          tables: [
            TableDefinition(
              name: 'audit_log',
              dartName: 'AuditLog',
              schema: 'public',
              columns: [
                ColumnDefinition(
                  name: 'id',
                  columnType: ColumnType.bigint,
                  isNullable: false,
                  columnDefault: defaultIntSerial,
                ),
                ColumnDefinition(
                  name: 'event',
                  columnType: ColumnType.text,
                  isNullable: false,
                ),
              ],
              foreignKeys: const [],
              indexes: [
                IndexDefinition(
                  indexName: 'audit_log_event_idx',
                  elements: [
                    IndexElementDefinition(
                      type: IndexElementDefinitionType.column,
                      definition: 'event',
                    ),
                  ],
                  type: 'btree',
                  isUnique: false,
                  isPrimary: false,
                ),
              ],
            ),
          ],
          installedModules: const [],
          migrationApiVersion: 1,
        ),
        installedModules: const [],
        removedModules: const [],
      );

      expect(
        sql,
        equals('''
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB\$RELATIONS WHERE RDB\$RELATION_NAME = 'AUDIT_LOG' AND COALESCE(RDB\$SYSTEM_FLAG, 0) = 0)) THEN
  BEGIN
    EXECUTE STATEMENT 'CREATE TABLE "AUDIT_LOG" (
  "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "EVENT" VARCHAR(255) CHARACTER SET UTF8 NOT NULL
)';
    EXECUTE STATEMENT 'CREATE INDEX "AUDIT_LOG_EVENT_IDX" ON "AUDIT_LOG" ("EVENT")';
  END
END;
'''),
      );
    });

    test(
      'uses Firebird-native indexed-text storage profiles for auth-style keys',
      () {
        final databaseDefinition = DatabaseDefinition(
          moduleName: 'app',
          tables: [
            TableDefinition(
              name: 'identity',
              dartName: 'Identity',
              schema: 'public',
              columns: [
                ColumnDefinition(
                  name: 'id',
                  columnType: ColumnType.bigint,
                  isNullable: false,
                  columnDefault: defaultIntSerial,
                ),
                ColumnDefinition(
                  name: 'email',
                  columnType: ColumnType.text,
                  isNullable: false,
                ),
                ColumnDefinition(
                  name: 'userIdentifier',
                  columnType: ColumnType.text,
                  isNullable: false,
                ),
                ColumnDefinition(
                  name: 'keyIdBase64',
                  columnType: ColumnType.text,
                  isNullable: false,
                ),
              ],
              foreignKeys: const [],
              indexes: [
                IndexDefinition(
                  indexName: 'identity_email_idx',
                  elements: [
                    IndexElementDefinition(
                      type: IndexElementDefinitionType.column,
                      definition: 'email',
                    ),
                  ],
                  type: 'btree',
                  isUnique: true,
                  isPrimary: false,
                ),
                IndexDefinition(
                  indexName: 'identity_user_identifier_idx',
                  elements: [
                    IndexElementDefinition(
                      type: IndexElementDefinitionType.column,
                      definition: 'userIdentifier',
                    ),
                  ],
                  type: 'btree',
                  isUnique: true,
                  isPrimary: false,
                ),
                IndexDefinition(
                  indexName: 'identity_key_id_base64_idx',
                  elements: [
                    IndexElementDefinition(
                      type: IndexElementDefinitionType.column,
                      definition: 'keyIdBase64',
                    ),
                  ],
                  type: 'btree',
                  isUnique: true,
                  isPrimary: false,
                ),
              ],
            ),
            TableDefinition(
              name: 'rate_limit',
              dartName: 'RateLimit',
              schema: 'public',
              columns: [
                ColumnDefinition(
                  name: 'id',
                  columnType: ColumnType.bigint,
                  isNullable: false,
                  columnDefault: defaultIntSerial,
                ),
                ColumnDefinition(
                  name: 'domain',
                  columnType: ColumnType.text,
                  isNullable: false,
                ),
                ColumnDefinition(
                  name: 'source',
                  columnType: ColumnType.text,
                  isNullable: false,
                ),
                ColumnDefinition(
                  name: 'nonce',
                  columnType: ColumnType.text,
                  isNullable: false,
                ),
                ColumnDefinition(
                  name: 'attemptedAt',
                  columnType: ColumnType.timestampWithoutTimeZone,
                  isNullable: false,
                ),
              ],
              foreignKeys: const [],
              indexes: [
                IndexDefinition(
                  indexName: 'rate_limit_composite_idx',
                  elements: [
                    IndexElementDefinition(
                      type: IndexElementDefinitionType.column,
                      definition: 'domain',
                    ),
                    IndexElementDefinition(
                      type: IndexElementDefinitionType.column,
                      definition: 'source',
                    ),
                    IndexElementDefinition(
                      type: IndexElementDefinitionType.column,
                      definition: 'nonce',
                    ),
                    IndexElementDefinition(
                      type: IndexElementDefinitionType.column,
                      definition: 'attemptedAt',
                    ),
                  ],
                  type: 'btree',
                  isUnique: false,
                  isPrimary: false,
                ),
              ],
            ),
          ],
          installedModules: const [],
          migrationApiVersion: 1,
        );

        final sql = generator.generateDatabaseDefinitionSql(
          databaseDefinition,
          installedModules: const [],
        );

        expect(
          sql,
          contains('"EMAIL" VARCHAR(320) CHARACTER SET ASCII NOT NULL'),
        );
        expect(
          sql,
          contains(
            '"USERIDENTIFIER" VARCHAR(512) CHARACTER SET ASCII NOT NULL',
          ),
        );
        expect(
          sql,
          contains('"KEYIDBASE64" VARCHAR(512) CHARACTER SET ASCII NOT NULL'),
        );
        expect(
          sql,
          contains('"DOMAIN" VARCHAR(96) CHARACTER SET ASCII NOT NULL'),
        );
        expect(
          sql,
          contains('"SOURCE" VARCHAR(96) CHARACTER SET ASCII NOT NULL'),
        );
        expect(
          sql,
          contains('"NONCE" VARCHAR(255) CHARACTER SET ASCII NOT NULL'),
        );
      },
    );

    test('treats compatibility-uppercase ID columns as primary keys', () {
      final databaseDefinition = DatabaseDefinition(
        moduleName: 'app',
        tables: [
          TableDefinition(
            name: 'AUTH_USER',
            dartName: 'AuthUser',
            schema: 'public',
            columns: [
              ColumnDefinition(
                name: 'ID',
                columnType: ColumnType.uuid,
                isNullable: false,
              ),
            ],
            foreignKeys: const [],
            indexes: const [],
          ),
          TableDefinition(
            name: 'AUTH_LOGIN',
            dartName: 'AuthLogin',
            schema: 'public',
            columns: [
              ColumnDefinition(
                name: 'ID',
                columnType: ColumnType.uuid,
                isNullable: false,
              ),
              ColumnDefinition(
                name: 'AUTHUSERID',
                columnType: ColumnType.uuid,
                isNullable: false,
              ),
            ],
            foreignKeys: [
              ForeignKeyDefinition(
                constraintName: 'AUTH_LOGIN_FK_0',
                columns: const ['AUTHUSERID'],
                referenceTable: 'AUTH_USER',
                referenceTableSchema: 'public',
                referenceColumns: const ['ID'],
              ),
            ],
            indexes: const [],
          ),
        ],
        installedModules: const [],
        migrationApiVersion: 1,
      );

      final sql = generator.generateDatabaseDefinitionSql(
        databaseDefinition,
        installedModules: const [],
      );

      expect(sql, contains('"ID" CHAR(36) CHARACTER SET ASCII PRIMARY KEY'));
      expect(
        sql,
        contains(
          'ALTER TABLE "AUTH_LOGIN" ADD CONSTRAINT "AUTH_LOGIN_FK_0" '
          'FOREIGN KEY ("AUTHUSERID") REFERENCES "AUTH_USER" ("ID")',
        ),
      );
    });

    test('generates alter table migration SQL for supported operations', () {
      final targetDefinition = DatabaseDefinition(
        moduleName: 'app',
        tables: [
          TableDefinition(
            name: 'task',
            dartName: 'Task',
            schema: 'public',
            columns: [
              ColumnDefinition(
                name: 'id',
                columnType: ColumnType.bigint,
                isNullable: false,
                columnDefault: defaultIntSerial,
              ),
              ColumnDefinition(
                name: 'title',
                columnType: ColumnType.text,
                isNullable: false,
              ),
              ColumnDefinition(
                name: 'createdAt',
                columnType: ColumnType.timestampWithoutTimeZone,
                isNullable: false,
                columnDefault: defaultDateTimeValueNow,
              ),
              ColumnDefinition(
                name: 'ownerId',
                columnType: ColumnType.bigint,
                isNullable: true,
              ),
            ],
            foreignKeys: [
              ForeignKeyDefinition(
                constraintName: 'task_owner_fk',
                columns: const ['ownerId'],
                referenceTable: 'app_user',
                referenceTableSchema: 'public',
                referenceColumns: const ['id'],
                onDelete: ForeignKeyAction.setNull,
              ),
            ],
            indexes: [
              IndexDefinition(
                indexName: 'task_title_idx',
                elements: [
                  IndexElementDefinition(
                    type: IndexElementDefinitionType.column,
                    definition: 'title',
                  ),
                ],
                type: 'btree',
                isUnique: false,
                isPrimary: false,
              ),
            ],
          ),
        ],
        installedModules: const [],
        migrationApiVersion: 1,
      );

      final databaseMigration = DatabaseMigration(
        actions: [
          DatabaseMigrationAction(
            type: DatabaseMigrationActionType.alterTable,
            alterTable: TableMigration(
              name: 'task',
              schema: 'public',
              addColumns: [
                ColumnDefinition(
                  name: 'createdAt',
                  columnType: ColumnType.timestampWithoutTimeZone,
                  isNullable: false,
                  columnDefault: defaultDateTimeValueNow,
                ),
              ],
              deleteColumns: const ['legacyTitle'],
              modifyColumns: [
                ColumnMigration(
                  columnName: 'ownerId',
                  addNullable: false,
                  removeNullable: true,
                  changeDefault: false,
                ),
                ColumnMigration(
                  columnName: 'title',
                  addNullable: false,
                  removeNullable: false,
                  changeDefault: true,
                  newDefault: null,
                ),
              ],
              renameColumns: const {'name': 'title'},
              addIndexes: [
                IndexDefinition(
                  indexName: 'task_title_idx',
                  elements: [
                    IndexElementDefinition(
                      type: IndexElementDefinitionType.column,
                      definition: 'title',
                    ),
                  ],
                  type: 'btree',
                  isUnique: false,
                  isPrimary: false,
                ),
              ],
              deleteIndexes: const ['task_old_name_idx'],
              addForeignKeys: [
                ForeignKeyDefinition(
                  constraintName: 'task_owner_fk',
                  columns: const ['ownerId'],
                  referenceTable: 'app_user',
                  referenceTableSchema: 'public',
                  referenceColumns: const ['id'],
                  onDelete: ForeignKeyAction.setNull,
                ),
              ],
              deleteForeignKeys: const ['task_old_fk'],
              warnings: const [],
            ),
          ),
        ],
        warnings: const [],
        migrationApiVersion: 1,
      );

      final sql = generator.generateDatabaseMigrationSql(
        databaseMigration,
        targetDefinition,
        installedModules: [
          DatabaseMigrationVersionModel(module: 'app', version: '202604160002'),
        ],
        removedModules: [
          DatabaseMigrationVersionModel(
            module: 'old_module',
            version: '202604150999',
          ),
        ],
      );

      expect(
        sql,
        equals('''
DROP INDEX "TASK_OLD_NAME_IDX";
ALTER TABLE "TASK" DROP CONSTRAINT "TASK_OLD_FK";
ALTER TABLE "TASK" DROP "LEGACYTITLE";
ALTER TABLE "TASK" ALTER COLUMN "NAME" TO "TITLE";
ALTER TABLE "TASK" ADD "CREATEDAT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE "TASK" ALTER COLUMN "OWNERID" SET NOT NULL;
ALTER TABLE "TASK" ALTER COLUMN "TITLE" DROP DEFAULT;
CREATE INDEX "TASK_TITLE_IDX" ON "TASK" ("TITLE");
ALTER TABLE "TASK" ADD CONSTRAINT "TASK_OWNER_FK" FOREIGN KEY ("OWNERID") REFERENCES "APP_USER" ("ID") ON DELETE SET NULL;

DELETE FROM "SERVERPOD_MIGRATIONS" WHERE "MODULE" = 'old_module';
UPDATE OR INSERT INTO "SERVERPOD_MIGRATIONS" ("MODULE", "VERSION", "TIMESTAMP") VALUES ('app', '202604160002', CURRENT_TIMESTAMP) MATCHING ("MODULE");
'''),
      );
    });

    test('rejects unsupported Firebird schema features clearly', () {
      final databaseDefinition = DatabaseDefinition(
        moduleName: 'app',
        tables: [
          TableDefinition(
            name: 'vector_table',
            dartName: 'VectorTable',
            schema: 'custom_schema',
            columns: [
              ColumnDefinition(
                name: 'id',
                columnType: ColumnType.bigint,
                isNullable: false,
                columnDefault: defaultIntSerial,
              ),
            ],
            foreignKeys: const [],
            indexes: const [],
          ),
        ],
        installedModules: const [],
        migrationApiVersion: 1,
      );

      expect(
        () => generator.generateDatabaseDefinitionSql(
          databaseDefinition,
          installedModules: const [],
        ),
        throwsA(
          isA<UnsupportedError>().having(
            (error) => error.message,
            'message',
            contains('supports only the "public" Serverpod schema mapping'),
          ),
        ),
      );
    });

    test('omits random UUID database defaults in Firebird schema SQL', () {
      DatabaseDefinition buildDefinition(String defaultValue) {
        return DatabaseDefinition(
          moduleName: 'app',
          tables: [
            TableDefinition(
              name: 'uuid_table',
              dartName: 'UuidTable',
              schema: 'public',
              columns: [
                ColumnDefinition(
                  name: 'id',
                  columnType: ColumnType.bigint,
                  isNullable: false,
                  columnDefault: defaultIntSerial,
                ),
                ColumnDefinition(
                  name: 'publicId',
                  columnType: ColumnType.uuid,
                  isNullable: false,
                  columnDefault: defaultValue,
                ),
              ],
              foreignKeys: const [],
              indexes: const [],
            ),
          ],
          installedModules: const [],
          migrationApiVersion: 1,
        );
      }

      final randomSql = generator.generateDatabaseDefinitionSql(
        buildDefinition(defaultUuidValueRandom),
        installedModules: const [],
      );
      final randomV7Sql = generator.generateDatabaseDefinitionSql(
        buildDefinition(defaultUuidValueRandomV7),
        installedModules: const [],
      );

      expect(
        randomSql,
        contains('"PUBLICID" CHAR(36) CHARACTER SET ASCII NOT NULL'),
      );
      expect(
        randomV7Sql,
        contains('"PUBLICID" CHAR(36) CHARACTER SET ASCII NOT NULL'),
      );
      expect(
        randomSql,
        isNot(contains('"PUBLICID" CHAR(36) CHARACTER SET ASCII DEFAULT')),
      );
      expect(
        randomV7Sql,
        isNot(contains('"PUBLICID" CHAR(36) CHARACTER SET ASCII DEFAULT')),
      );
    });
  });
}
