import 'package:firebirdpod/firebirdpod.dart';
import 'package:test/test.dart';

import 'firebird_test_support.dart';

const _tableName = 'FIREBIRDPOD_POOL_RESET_ITEM';

void main() {
  group('Phase 01 pooled connection reset', () {
    setUpAll(() async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await _openConnection(
        statementTimeout: const Duration(milliseconds: 250),
      );
      try {
        await _dropTableIfExists(connection, _tableName);
        await connection.execute('''
          create table $_tableName (
            ID integer generated by default as identity primary key,
            NAME varchar(50) not null
          )
        ''');
      } finally {
        await connection.close();
      }
    });

    tearDownAll(() async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await _openConnection(
        statementTimeout: const Duration(milliseconds: 250),
      );
      try {
        await _dropTableIfExists(connection, _tableName);
      } finally {
        await connection.close();
      }
    });

    setUp(() async {
      if (!shouldRunDirectIntegrationTests()) {
        return;
      }

      final connection = await _openConnection(
        statementTimeout: const Duration(milliseconds: 250),
      );
      try {
        await connection.execute('delete from $_tableName');
        await connection.execute(
          'alter table $_tableName alter ID restart with 1',
        );
      } finally {
        await connection.close();
      }
    });

    test(
      'resetForReuse recreates retained state restores timeout and rolls back leaked transaction work',
      () async {
        if (!shouldRunDirectIntegrationTests()) {
          return;
        }

        final connection = await _openConnection(
          statementTimeout: const Duration(milliseconds: 250),
        );
        addTearDown(connection.close);

        final statement = await connection.prepare(
          'select 1 as ONE_VALUE from rdb\$database',
        );

        await connection.execute(
          '''
          select rdb\$set_context('USER_TRANSACTION', \$1, \$2) as APPLIED
          from rdb\$database
          ''',
          parameters: FirebirdStatementParameters.positional([
            'LEASE_MARKER',
            'dirty',
          ]),
        );

        final transaction = await connection.beginTransaction();
        await transaction.execute(
          'insert into $_tableName (NAME) values (\$1)',
          parameters: FirebirdStatementParameters.positional(['pending']),
        );

        await connection.setStatementTimeout(const Duration(milliseconds: 90));
        await connection.resetForReuse();

        expect(statement.isClosed, isTrue);
        expect(transaction.isRolledBack, isTrue);
        expect(transaction.isClosed, isTrue);

        final contextValue = await connection.execute(
          '''
          select rdb\$get_context('USER_TRANSACTION', \$1) as CTX_VALUE
          from rdb\$database
          ''',
          parameters: FirebirdStatementParameters.positional(['LEASE_MARKER']),
        );
        final rowCount = await connection.execute(
          'select count(*) as CNT from $_tableName',
        );

        expect(contextValue.singleRow?['CTX_VALUE'], anyOf(isNull, ''));
        expect(rowCount.singleRow?['CNT'], 0);
      },
    );
  });
}

Future<FirebirdConnection> _openConnection({
  required Duration statementTimeout,
}) async {
  return buildDirectEndpoint(
    database: firebirdTestDatabasePath(),
    statementTimeout: statementTimeout,
  ).connect();
}

Future<void> _dropTableIfExists(
  FirebirdConnection connection,
  String tableName,
) async {
  try {
    await connection.execute('drop table $tableName');
  } catch (_) {}
}
