import 'dart:math' as math;

import 'package:serverpod_database/serverpod_database.dart';

import 'firebird_serverpod_default_value.dart';

/// Firebird-native schema and migration SQL generation for Serverpod.
class FirebirdServerpodSqlGenerator {
  const FirebirdServerpodSqlGenerator();

  /// Generates the baseline Firebird schema definition SQL for [databaseDefinition].
  String generateDatabaseDefinitionSql(
    DatabaseDefinition databaseDefinition, {
    required List<DatabaseMigrationVersionModel> installedModules,
  }) {
    return databaseDefinition.toFirebirdSql(installedModules: installedModules);
  }

  /// Generates Firebird migration SQL for [databaseMigration].
  String generateDatabaseMigrationSql(
    DatabaseMigration databaseMigration,
    DatabaseDefinition databaseDefinition, {
    required List<DatabaseMigrationVersionModel> installedModules,
    required List<DatabaseMigrationVersionModel> removedModules,
  }) {
    return databaseMigration.toFirebirdSql(
      databaseDefinition: databaseDefinition,
      installedModules: installedModules,
      removedModules: removedModules,
    );
  }
}

extension FirebirdDatabaseDefinitionSqlGeneration on DatabaseDefinition {
  /// Converts the target [DatabaseDefinition] into deterministic Firebird SQL.
  String toFirebirdSql({
    required List<DatabaseMigrationVersionModel> installedModules,
  }) {
    final managedTables = tables
        .where((table) => table.managed != false)
        .toList(growable: false);
    final buffer = StringBuffer();

    for (final table in managedTables) {
      buffer.writeln('--');
      buffer.writeln(
        '-- Class ${table.dartName ?? table.name} as table ${table.name}',
      );
      buffer.writeln('--');
      buffer.writeln('${_tableBaseCreationStatement(table)};');
      buffer.writeln();
    }

    for (final table in managedTables) {
      for (final foreignKeyStatement in _tableForeignKeyStatements(table)) {
        buffer.writeln('$foreignKeyStatement;');
      }
    }

    if (managedTables.any((table) => table.foreignKeys.isNotEmpty)) {
      buffer.writeln();
    }

    for (final table in managedTables) {
      for (final indexStatement in _tableIndexStatements(table)) {
        buffer.writeln('$indexStatement;');
      }
    }

    if (managedTables.any(
      (table) => table.indexes.any((index) => !_isInlinePrimaryKeyIndex(index)),
    )) {
      buffer.writeln();
    }

    for (final module in installedModules) {
      buffer.writeln(
        _sqlStoreMigrationVersion(
          module: module.module,
          version: module.version,
          timestamp: module.timestamp,
        ),
      );
    }

    return '${buffer.toString().trimRight()}\n';
  }
}

extension FirebirdTableDefinitionSqlGeneration on TableDefinition {
  /// Converts this [TableDefinition] into Firebird SQL.
  String tableCreationToFirebirdSql({bool ifNotExists = false}) {
    _validateTableDefinition(this);
    final statements = _tableCreationStatements(this);

    if (!ifNotExists) {
      return statements.map((statement) => '$statement;\n').join();
    }

    return _wrapStatementsIfTableMissing(name, statements);
  }
}

extension FirebirdColumnDefinitionSqlGeneration on ColumnDefinition {
  /// Whether the column should be emitted as a Firebird identity column.
  bool get isIdentityColumn =>
      (columnType == ColumnType.integer || columnType == ColumnType.bigint) &&
      columnDefault == defaultIntSerial;

  /// Converts this [ColumnDefinition] into a Firebird column fragment.
  String toFirebirdSqlFragment({
    ({String characterSet, int length})? indexedTextProfile,
  }) {
    final isPrimaryKeyColumn = _isPrimaryKeyColumn(this);

    if (isPrimaryKeyColumn && isNullable) {
      throw const FormatException('The id column must be non-nullable');
    }

    final type = switch (columnType) {
      ColumnType.bigint => 'BIGINT',
      ColumnType.boolean => 'BOOLEAN',
      ColumnType.bytea => 'BLOB SUB_TYPE BINARY',
      ColumnType.doublePrecision => 'DOUBLE PRECISION',
      ColumnType.integer => 'INTEGER',
      ColumnType.json => 'BLOB SUB_TYPE TEXT CHARACTER SET UTF8',
      ColumnType.text =>
        indexedTextProfile != null
            ? 'VARCHAR(${indexedTextProfile.length}) CHARACTER SET '
                  '${indexedTextProfile.characterSet}'
            : 'BLOB SUB_TYPE TEXT CHARACTER SET UTF8',
      ColumnType.timestampWithoutTimeZone => 'TIMESTAMP',
      ColumnType.uuid => 'CHAR(36) CHARACTER SET ASCII',
      ColumnType.unknown => throw const FormatException('Unknown column type'),
      ColumnType.vector ||
      ColumnType.halfvec ||
      ColumnType.sparsevec ||
      ColumnType.bit => throw UnsupportedError(
        'Firebird schema generation does not support vector column type '
        '$columnType yet.',
      ),
    };

    final parts = <String>[_renderIdentifier(name), type];

    if (isIdentityColumn) {
      parts.add('GENERATED BY DEFAULT AS IDENTITY');
    }

    final defaultSql = columnType.getFirebirdColumnDefault(columnDefault);
    if (defaultSql != null) {
      parts.add('DEFAULT $defaultSql');
    }

    if (!isNullable && !isIdentityColumn && !isPrimaryKeyColumn) {
      parts.add('NOT NULL');
    }

    if (isPrimaryKeyColumn) {
      parts.add('PRIMARY KEY');
    }

    return parts.join(' ');
  }
}

extension FirebirdIndexDefinitionSqlGeneration on IndexDefinition {
  /// Converts this [IndexDefinition] into Firebird SQL.
  String toFirebirdSql({required String tableName}) {
    _validateIndexDefinition(this);

    if (isPrimary) {
      throw UnsupportedError(
        'Firebird schema generation expects primary keys to be emitted as '
        'column definitions or explicit table constraints, not standalone '
        'indexes.',
      );
    }

    final uniquePrefix = isUnique ? 'UNIQUE ' : '';
    final elementsSql = elements
        .map(
          (element) => switch (element.type) {
            IndexElementDefinitionType.column => _renderIdentifier(
              element.definition,
            ),
            IndexElementDefinitionType.expression => throw UnsupportedError(
              'Firebird schema generation does not support expression '
              'indexes yet.',
            ),
          },
        )
        .join(', ');

    return 'CREATE ${uniquePrefix}INDEX ${_renderIdentifier(indexName)} ON '
        '${_renderIdentifier(tableName)} '
        '($elementsSql)';
  }
}

extension FirebirdForeignKeyDefinitionSqlGeneration on ForeignKeyDefinition {
  /// Converts this [ForeignKeyDefinition] into an inline Firebird constraint.
  String toFirebirdInlineSql() {
    _validateForeignKeyDefinition(this);

    final columnsSql = columns.map(_renderIdentifier).join(', ');
    final referenceColumnsSql = referenceColumns
        .map(_renderIdentifier)
        .join(', ');

    final parts = <String>[
      'CONSTRAINT ${_renderIdentifier(constraintName)}',
      'FOREIGN KEY ($columnsSql)',
      'REFERENCES ${_renderIdentifier(referenceTable)} ($referenceColumnsSql)',
    ];

    if (matchType != null && matchType != ForeignKeyMatchType.simple) {
      parts.add('MATCH ${_foreignKeyMatchTypeSql(matchType!)}');
    }

    if (onDelete != null) {
      parts.add('ON DELETE ${_foreignKeyActionSql(onDelete!)}');
    }

    if (onUpdate != null) {
      parts.add('ON UPDATE ${_foreignKeyActionSql(onUpdate!)}');
    }

    return parts.join(' ');
  }
}

extension FirebirdDatabaseMigrationSqlGeneration on DatabaseMigration {
  /// Converts this [DatabaseMigration] into Firebird SQL.
  String toFirebirdSql({
    required DatabaseDefinition databaseDefinition,
    required List<DatabaseMigrationVersionModel> installedModules,
    required List<DatabaseMigrationVersionModel> removedModules,
  }) {
    final buffer = StringBuffer();

    for (final action in actions) {
      buffer.write(
        action.toFirebirdSql(databaseDefinition: databaseDefinition),
      );
      buffer.writeln();
    }

    for (final module in removedModules) {
      buffer.writeln(_sqlDeleteMigrationVersion(module: module.module));
    }

    for (final module in installedModules) {
      buffer.writeln(
        _sqlStoreMigrationVersion(
          module: module.module,
          version: module.version,
          timestamp: module.timestamp,
        ),
      );
    }

    return '${buffer.toString().trimRight()}\n';
  }
}

extension FirebirdDatabaseMigrationActionSqlGeneration
    on DatabaseMigrationAction {
  /// Converts this migration action into Firebird SQL.
  String toFirebirdSql({required DatabaseDefinition databaseDefinition}) {
    return switch (type) {
      DatabaseMigrationActionType.createTable =>
        _requireCreateTable().tableCreationToFirebirdSql(),
      DatabaseMigrationActionType.createTableIfNotExists =>
        _requireCreateTable().tableCreationToFirebirdSql(ifNotExists: true),
      DatabaseMigrationActionType.deleteTable => _sqlDropTable(
        tableName: _requireDeleteTable(),
      ),
      DatabaseMigrationActionType.alterTable =>
        _requireAlterTable().toFirebirdSql(
          databaseDefinition: databaseDefinition,
        ),
    };
  }

  TableDefinition _requireCreateTable() {
    final table = createTable;
    if (table == null) {
      throw StateError(
        'Missing createTable definition for migration action $type.',
      );
    }
    return table;
  }

  String _requireDeleteTable() {
    final tableName = deleteTable;
    if (tableName == null) {
      throw StateError('Missing deleteTable name for migration action $type.');
    }
    return tableName;
  }

  TableMigration _requireAlterTable() {
    final table = alterTable;
    if (table == null) {
      throw StateError(
        'Missing alterTable definition for migration action $type.',
      );
    }
    return table;
  }
}

extension FirebirdTableMigrationSqlGeneration on TableMigration {
  /// Converts this [TableMigration] into Firebird SQL.
  String toFirebirdSql({required DatabaseDefinition databaseDefinition}) {
    _validateSchema(schema: schema, objectType: 'table', objectName: name);

    final targetTable = databaseDefinition.findTableNamed(name);
    if (targetTable == null) {
      throw StateError(
        'Could not find target table "$name" in the database definition.',
      );
    }

    final statements = <String>[];

    for (final indexName in deleteIndexes) {
      statements.add('DROP INDEX ${_renderIdentifier(indexName)}');
    }

    for (final keyName in deleteForeignKeys) {
      statements.add(
        'ALTER TABLE ${_renderIdentifier(name)} DROP CONSTRAINT '
        '${_renderIdentifier(keyName)}',
      );
    }

    for (final columnName in deleteColumns) {
      statements.add(
        'ALTER TABLE ${_renderIdentifier(name)} DROP '
        '${_renderIdentifier(columnName)}',
      );
    }

    final renameColumnsEntries = renameColumns?.entries.toList() ?? const [];
    for (final entry in renameColumnsEntries) {
      statements.add(
        'ALTER TABLE ${_renderIdentifier(name)} ALTER COLUMN '
        '${_renderIdentifier(entry.key)} TO ${_renderIdentifier(entry.value)}',
      );
    }

    final indexedTextProfiles = _tableIndexedTextProfiles(targetTable);
    for (final column in addColumns) {
      statements.add(
        'ALTER TABLE ${_renderIdentifier(name)} ADD '
        '${column.toFirebirdSqlFragment(indexedTextProfile: indexedTextProfiles[column.name])}',
      );
    }

    for (final column in modifyColumns) {
      final targetColumn = targetTable.findColumnNamed(column.columnName);
      if (targetColumn == null) {
        throw StateError(
          'Could not find target column "${column.columnName}" in table '
          '"${targetTable.name}".',
        );
      }

      if (column.changeDefault) {
        if (column.newDefault == null) {
          statements.add(
            'ALTER TABLE ${_renderIdentifier(name)} ALTER COLUMN '
            '${_renderIdentifier(column.columnName)} '
            'DROP DEFAULT',
          );
        } else {
          final defaultSql = targetColumn.columnType.getFirebirdColumnDefault(
            column.newDefault,
          );
          if (defaultSql == null) {
            throw UnsupportedError(
              'Firebird migration generation cannot set a NULL default for '
              'column "${column.columnName}".',
            );
          }
          statements.add(
            'ALTER TABLE ${_renderIdentifier(name)} ALTER COLUMN '
            '${_renderIdentifier(column.columnName)} '
            'SET DEFAULT $defaultSql',
          );
        }
      }

      if (column.removeNullable) {
        statements.add(
          'ALTER TABLE ${_renderIdentifier(name)} ALTER COLUMN '
          '${_renderIdentifier(column.columnName)} '
          'SET NOT NULL',
        );
      }

      if (column.addNullable) {
        statements.add(
          'ALTER TABLE ${_renderIdentifier(name)} ALTER COLUMN '
          '${_renderIdentifier(column.columnName)} '
          'DROP NOT NULL',
        );
      }
    }

    for (final index in addIndexes) {
      if (index.isPrimary) {
        throw UnsupportedError(
          'Firebird migration generation does not support adding new primary '
          'key indexes in the first Phase 03 slice.',
        );
      }
      statements.add(index.toFirebirdSql(tableName: name));
    }

    for (final foreignKey in addForeignKeys) {
      statements.add(
        'ALTER TABLE ${_renderIdentifier(name)} ADD '
        '${foreignKey.toFirebirdInlineSql()}',
      );
    }

    return statements.map((statement) => '$statement;\n').join();
  }
}

void _validateTableDefinition(TableDefinition table) {
  _validateSchema(
    schema: table.schema,
    objectType: 'table',
    objectName: table.name,
  );

  if (table.tableSpace != null) {
    throw UnsupportedError(
      'Firebird schema generation does not support tablespaces for table '
      '"${table.name}".',
    );
  }

  for (final foreignKey in table.foreignKeys) {
    _validateForeignKeyDefinition(foreignKey);
  }

  for (final index in table.indexes) {
    if (_isInlinePrimaryKeyIndex(index)) {
      continue;
    }

    _validateIndexDefinition(index);
  }
}

void _validateIndexDefinition(IndexDefinition index) {
  if (index.type != 'btree') {
    throw UnsupportedError(
      'Firebird schema generation does not support index type "${index.type}" '
      'for index "${index.indexName}".',
    );
  }

  if (index.tableSpace != null) {
    throw UnsupportedError(
      'Firebird schema generation does not support index tablespaces for '
      'index "${index.indexName}".',
    );
  }

  if (index.predicate != null) {
    throw UnsupportedError(
      'Firebird schema generation does not support partial indexes for '
      'index "${index.indexName}" yet.',
    );
  }

  if (index.vectorDistanceFunction != null || index.vectorColumnType != null) {
    throw UnsupportedError(
      'Firebird schema generation does not support vector indexes for '
      'index "${index.indexName}" yet.',
    );
  }

  if (index.parameters != null && index.parameters!.isNotEmpty) {
    throw UnsupportedError(
      'Firebird schema generation does not support custom index parameters '
      'for index "${index.indexName}" yet.',
    );
  }
}

void _validateForeignKeyDefinition(ForeignKeyDefinition foreignKey) {
  _validateSchema(
    schema: foreignKey.referenceTableSchema,
    objectType: 'referenced table',
    objectName: foreignKey.referenceTable,
  );
}

void _validateSchema({
  required String schema,
  required String objectType,
  required String objectName,
}) {
  if (schema.toLowerCase() != 'public') {
    throw UnsupportedError(
      'Firebird schema generation currently supports only the "public" '
      'Serverpod schema mapping. Found schema "$schema" for $objectType '
      '"$objectName".',
    );
  }
}

List<String> _tableCreationStatements(TableDefinition table) {
  final statements = <String>[
    _tableBaseCreationStatement(table),
    ..._tableForeignKeyStatements(table),
    ..._tableIndexStatements(table),
  ];

  return statements;
}

String _tableBaseCreationStatement(TableDefinition table) {
  _validateTableDefinition(table);
  final indexedTextProfiles = _tableIndexedTextProfiles(table);
  final definitions = <String>[
    for (final column in table.columns)
      '  ${column.toFirebirdSqlFragment(indexedTextProfile: indexedTextProfiles[column.name])}',
  ];

  return 'CREATE TABLE ${_renderIdentifier(table.name)} '
      '(\n${definitions.join(',\n')}\n)';
}

Iterable<String> _tableForeignKeyStatements(TableDefinition table) sync* {
  for (final foreignKey in table.foreignKeys) {
    yield 'ALTER TABLE ${_renderIdentifier(table.name)} ADD '
        '${foreignKey.toFirebirdInlineSql()}';
  }
}

Iterable<String> _tableIndexStatements(TableDefinition table) sync* {
  for (final index in table.indexes) {
    if (_isInlinePrimaryKeyIndex(index)) {
      continue;
    }

    yield index.toFirebirdSql(tableName: table.name);
  }
}

bool _isInlinePrimaryKeyIndex(IndexDefinition index) {
  if (!index.isPrimary) return false;

  return index.elements.length == 1 &&
      index.elements.first.type == IndexElementDefinitionType.column &&
      index.elements.first.definition.toLowerCase() == defaultPrimaryKeyName;
}

bool _isPrimaryKeyColumn(ColumnDefinition column) {
  return column.name.toLowerCase() == defaultPrimaryKeyName;
}

Map<String, ({String characterSet, int length})> _tableIndexedTextProfiles(
  TableDefinition table,
) {
  final indexedTextProfiles = <String, ({String characterSet, int length})>{};

  for (final index in table.indexes) {
    if (_isInlinePrimaryKeyIndex(index)) {
      continue;
    }

    final isCompositeIndex = index.elements.length > 1;
    for (final element in index.elements) {
      if (element.type != IndexElementDefinitionType.column) {
        continue;
      }

      final column = table.findColumnNamed(element.definition);
      if (column == null || column.columnType != ColumnType.text) {
        continue;
      }

      final candidateProfile = _indexedTextProfileForColumn(
        columnName: column.name,
        isCompositeIndex: isCompositeIndex,
      );
      final currentProfile = indexedTextProfiles[column.name];
      indexedTextProfiles[column.name] = currentProfile == null
          ? candidateProfile
          : (
              characterSet: currentProfile.characterSet,
              length: math.min(currentProfile.length, candidateProfile.length),
            );
    }
  }

  return indexedTextProfiles;
}

({String characterSet, int length}) _indexedTextProfileForColumn({
  required String columnName,
  required bool isCompositeIndex,
}) {
  final normalizedName = columnName.toLowerCase();

  if (isCompositeIndex) {
    return switch (normalizedName) {
      'domain' => (characterSet: 'ASCII', length: 96),
      'source' => (characterSet: 'ASCII', length: 96),
      'nonce' => (characterSet: 'ASCII', length: 255),
      _ => (characterSet: 'UTF8', length: 160),
    };
  }

  if (normalizedName == 'email') {
    return (characterSet: 'ASCII', length: 320);
  }

  if (normalizedName == 'useridentifier' || normalizedName == 'keyidbase64') {
    return (characterSet: 'ASCII', length: 512);
  }

  return (characterSet: 'UTF8', length: 255);
}

String _wrapStatementsIfTableMissing(
  String tableName,
  List<String> statements,
) {
  final escapedStatements = statements
      .map((statement) => statement.replaceAll("'", "''"))
      .toList();

  final buffer = StringBuffer()
    ..writeln('EXECUTE BLOCK AS')
    ..writeln('BEGIN')
    ..writeln(
      '  IF (NOT EXISTS('
      "SELECT 1 FROM RDB\$RELATIONS "
      "WHERE RDB\$RELATION_NAME = '${tableName.toUpperCase()}' "
      'AND COALESCE(RDB\$SYSTEM_FLAG, 0) = 0'
      ')) THEN',
    )
    ..writeln('  BEGIN');

  for (final statement in escapedStatements) {
    buffer.writeln("    EXECUTE STATEMENT '$statement';");
  }

  buffer
    ..writeln('  END')
    ..write('END;\n');

  return buffer.toString();
}

String _sqlDropTable({required String tableName}) {
  return 'DROP TABLE ${_renderIdentifier(tableName)}';
}

String _sqlStoreMigrationVersion({
  required String module,
  required String version,
  DateTime? timestamp,
}) {
  final timestampSql = timestamp == null
      ? 'CURRENT_TIMESTAMP'
      : "TIMESTAMP '${timestamp.toUtc().toIso8601String().replaceFirst('T', ' ').replaceFirst('Z', '')}'";

  return 'UPDATE OR INSERT INTO ${_renderIdentifier("serverpod_migrations")} '
      '(${_renderIdentifier("module")}, ${_renderIdentifier("version")}, '
      '${_renderIdentifier("timestamp")}) '
      "VALUES ('${_escapeSqlLiteral(module)}', '${_escapeSqlLiteral(version)}', "
      '$timestampSql) MATCHING (${_renderIdentifier("module")});';
}

String _sqlDeleteMigrationVersion({required String module}) {
  return 'DELETE FROM ${_renderIdentifier("serverpod_migrations")} '
      "WHERE ${_renderIdentifier("module")} = '${_escapeSqlLiteral(module)}';";
}

String _escapeSqlLiteral(String value) => value.replaceAll("'", "''");

String _renderIdentifier(String identifier) =>
    '"${identifier.replaceAll('"', '""').toUpperCase()}"';

String _foreignKeyActionSql(ForeignKeyAction action) => switch (action) {
  ForeignKeyAction.noAction => 'NO ACTION',
  ForeignKeyAction.restrict => 'RESTRICT',
  ForeignKeyAction.cascade => 'CASCADE',
  ForeignKeyAction.setNull => 'SET NULL',
  ForeignKeyAction.setDefault => 'SET DEFAULT',
};

String _foreignKeyMatchTypeSql(ForeignKeyMatchType matchType) =>
    switch (matchType) {
      ForeignKeyMatchType.full => 'FULL',
      ForeignKeyMatchType.partial => 'PARTIAL',
      ForeignKeyMatchType.simple => 'SIMPLE',
    };
